// Code generated by counterfeiter. DO NOT EDIT.
package workflowfakes

import (
	"joblet/internal/joblet/workflow"
	"sync"
)

type FakeExpressionNode struct {
	CanBeSatisfiedStub        func(map[string]string, map[string]bool) bool
	canBeSatisfiedMutex       sync.RWMutex
	canBeSatisfiedArgsForCall []struct {
		arg1 map[string]string
		arg2 map[string]bool
	}
	canBeSatisfiedReturns struct {
		result1 bool
	}
	canBeSatisfiedReturnsOnCall map[int]struct {
		result1 bool
	}
	EvaluateStub        func(map[string]string) (bool, error)
	evaluateMutex       sync.RWMutex
	evaluateArgsForCall []struct {
		arg1 map[string]string
	}
	evaluateReturns struct {
		result1 bool
		result2 error
	}
	evaluateReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	GetJobNamesStub        func() []string
	getJobNamesMutex       sync.RWMutex
	getJobNamesArgsForCall []struct {
	}
	getJobNamesReturns struct {
		result1 []string
	}
	getJobNamesReturnsOnCall map[int]struct {
		result1 []string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeExpressionNode) CanBeSatisfied(arg1 map[string]string, arg2 map[string]bool) bool {
	fake.canBeSatisfiedMutex.Lock()
	ret, specificReturn := fake.canBeSatisfiedReturnsOnCall[len(fake.canBeSatisfiedArgsForCall)]
	fake.canBeSatisfiedArgsForCall = append(fake.canBeSatisfiedArgsForCall, struct {
		arg1 map[string]string
		arg2 map[string]bool
	}{arg1, arg2})
	stub := fake.CanBeSatisfiedStub
	fakeReturns := fake.canBeSatisfiedReturns
	fake.recordInvocation("CanBeSatisfied", []interface{}{arg1, arg2})
	fake.canBeSatisfiedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeExpressionNode) CanBeSatisfiedCallCount() int {
	fake.canBeSatisfiedMutex.RLock()
	defer fake.canBeSatisfiedMutex.RUnlock()
	return len(fake.canBeSatisfiedArgsForCall)
}

func (fake *FakeExpressionNode) CanBeSatisfiedCalls(stub func(map[string]string, map[string]bool) bool) {
	fake.canBeSatisfiedMutex.Lock()
	defer fake.canBeSatisfiedMutex.Unlock()
	fake.CanBeSatisfiedStub = stub
}

func (fake *FakeExpressionNode) CanBeSatisfiedArgsForCall(i int) (map[string]string, map[string]bool) {
	fake.canBeSatisfiedMutex.RLock()
	defer fake.canBeSatisfiedMutex.RUnlock()
	argsForCall := fake.canBeSatisfiedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeExpressionNode) CanBeSatisfiedReturns(result1 bool) {
	fake.canBeSatisfiedMutex.Lock()
	defer fake.canBeSatisfiedMutex.Unlock()
	fake.CanBeSatisfiedStub = nil
	fake.canBeSatisfiedReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeExpressionNode) CanBeSatisfiedReturnsOnCall(i int, result1 bool) {
	fake.canBeSatisfiedMutex.Lock()
	defer fake.canBeSatisfiedMutex.Unlock()
	fake.CanBeSatisfiedStub = nil
	if fake.canBeSatisfiedReturnsOnCall == nil {
		fake.canBeSatisfiedReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.canBeSatisfiedReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeExpressionNode) Evaluate(arg1 map[string]string) (bool, error) {
	fake.evaluateMutex.Lock()
	ret, specificReturn := fake.evaluateReturnsOnCall[len(fake.evaluateArgsForCall)]
	fake.evaluateArgsForCall = append(fake.evaluateArgsForCall, struct {
		arg1 map[string]string
	}{arg1})
	stub := fake.EvaluateStub
	fakeReturns := fake.evaluateReturns
	fake.recordInvocation("Evaluate", []interface{}{arg1})
	fake.evaluateMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeExpressionNode) EvaluateCallCount() int {
	fake.evaluateMutex.RLock()
	defer fake.evaluateMutex.RUnlock()
	return len(fake.evaluateArgsForCall)
}

func (fake *FakeExpressionNode) EvaluateCalls(stub func(map[string]string) (bool, error)) {
	fake.evaluateMutex.Lock()
	defer fake.evaluateMutex.Unlock()
	fake.EvaluateStub = stub
}

func (fake *FakeExpressionNode) EvaluateArgsForCall(i int) map[string]string {
	fake.evaluateMutex.RLock()
	defer fake.evaluateMutex.RUnlock()
	argsForCall := fake.evaluateArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeExpressionNode) EvaluateReturns(result1 bool, result2 error) {
	fake.evaluateMutex.Lock()
	defer fake.evaluateMutex.Unlock()
	fake.EvaluateStub = nil
	fake.evaluateReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeExpressionNode) EvaluateReturnsOnCall(i int, result1 bool, result2 error) {
	fake.evaluateMutex.Lock()
	defer fake.evaluateMutex.Unlock()
	fake.EvaluateStub = nil
	if fake.evaluateReturnsOnCall == nil {
		fake.evaluateReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.evaluateReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeExpressionNode) GetJobNames() []string {
	fake.getJobNamesMutex.Lock()
	ret, specificReturn := fake.getJobNamesReturnsOnCall[len(fake.getJobNamesArgsForCall)]
	fake.getJobNamesArgsForCall = append(fake.getJobNamesArgsForCall, struct {
	}{})
	stub := fake.GetJobNamesStub
	fakeReturns := fake.getJobNamesReturns
	fake.recordInvocation("GetJobNames", []interface{}{})
	fake.getJobNamesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeExpressionNode) GetJobNamesCallCount() int {
	fake.getJobNamesMutex.RLock()
	defer fake.getJobNamesMutex.RUnlock()
	return len(fake.getJobNamesArgsForCall)
}

func (fake *FakeExpressionNode) GetJobNamesCalls(stub func() []string) {
	fake.getJobNamesMutex.Lock()
	defer fake.getJobNamesMutex.Unlock()
	fake.GetJobNamesStub = stub
}

func (fake *FakeExpressionNode) GetJobNamesReturns(result1 []string) {
	fake.getJobNamesMutex.Lock()
	defer fake.getJobNamesMutex.Unlock()
	fake.GetJobNamesStub = nil
	fake.getJobNamesReturns = struct {
		result1 []string
	}{result1}
}

func (fake *FakeExpressionNode) GetJobNamesReturnsOnCall(i int, result1 []string) {
	fake.getJobNamesMutex.Lock()
	defer fake.getJobNamesMutex.Unlock()
	fake.GetJobNamesStub = nil
	if fake.getJobNamesReturnsOnCall == nil {
		fake.getJobNamesReturnsOnCall = make(map[int]struct {
			result1 []string
		})
	}
	fake.getJobNamesReturnsOnCall[i] = struct {
		result1 []string
	}{result1}
}

func (fake *FakeExpressionNode) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeExpressionNode) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ workflow.ExpressionNode = new(FakeExpressionNode)
