// Code generated by counterfeiter. DO NOT EDIT.
package executionfakes

import (
	"joblet/internal/joblet/core/execution"
	"sync"
)

type FakeIsolationManager struct {
	CreateBuilderEnvironmentStub        func(string) (*execution.IsolationContext, error)
	createBuilderEnvironmentMutex       sync.RWMutex
	createBuilderEnvironmentArgsForCall []struct {
		arg1 string
	}
	createBuilderEnvironmentReturns struct {
		result1 *execution.IsolationContext
		result2 error
	}
	createBuilderEnvironmentReturnsOnCall map[int]struct {
		result1 *execution.IsolationContext
		result2 error
	}
	CreateIsolatedEnvironmentStub        func(string) (*execution.IsolationContext, error)
	createIsolatedEnvironmentMutex       sync.RWMutex
	createIsolatedEnvironmentArgsForCall []struct {
		arg1 string
	}
	createIsolatedEnvironmentReturns struct {
		result1 *execution.IsolationContext
		result2 error
	}
	createIsolatedEnvironmentReturnsOnCall map[int]struct {
		result1 *execution.IsolationContext
		result2 error
	}
	DestroyIsolatedEnvironmentStub        func(string) error
	destroyIsolatedEnvironmentMutex       sync.RWMutex
	destroyIsolatedEnvironmentArgsForCall []struct {
		arg1 string
	}
	destroyIsolatedEnvironmentReturns struct {
		result1 error
	}
	destroyIsolatedEnvironmentReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeIsolationManager) CreateBuilderEnvironment(arg1 string) (*execution.IsolationContext, error) {
	fake.createBuilderEnvironmentMutex.Lock()
	ret, specificReturn := fake.createBuilderEnvironmentReturnsOnCall[len(fake.createBuilderEnvironmentArgsForCall)]
	fake.createBuilderEnvironmentArgsForCall = append(fake.createBuilderEnvironmentArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.CreateBuilderEnvironmentStub
	fakeReturns := fake.createBuilderEnvironmentReturns
	fake.recordInvocation("CreateBuilderEnvironment", []interface{}{arg1})
	fake.createBuilderEnvironmentMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeIsolationManager) CreateBuilderEnvironmentCallCount() int {
	fake.createBuilderEnvironmentMutex.RLock()
	defer fake.createBuilderEnvironmentMutex.RUnlock()
	return len(fake.createBuilderEnvironmentArgsForCall)
}

func (fake *FakeIsolationManager) CreateBuilderEnvironmentCalls(stub func(string) (*execution.IsolationContext, error)) {
	fake.createBuilderEnvironmentMutex.Lock()
	defer fake.createBuilderEnvironmentMutex.Unlock()
	fake.CreateBuilderEnvironmentStub = stub
}

func (fake *FakeIsolationManager) CreateBuilderEnvironmentArgsForCall(i int) string {
	fake.createBuilderEnvironmentMutex.RLock()
	defer fake.createBuilderEnvironmentMutex.RUnlock()
	argsForCall := fake.createBuilderEnvironmentArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeIsolationManager) CreateBuilderEnvironmentReturns(result1 *execution.IsolationContext, result2 error) {
	fake.createBuilderEnvironmentMutex.Lock()
	defer fake.createBuilderEnvironmentMutex.Unlock()
	fake.CreateBuilderEnvironmentStub = nil
	fake.createBuilderEnvironmentReturns = struct {
		result1 *execution.IsolationContext
		result2 error
	}{result1, result2}
}

func (fake *FakeIsolationManager) CreateBuilderEnvironmentReturnsOnCall(i int, result1 *execution.IsolationContext, result2 error) {
	fake.createBuilderEnvironmentMutex.Lock()
	defer fake.createBuilderEnvironmentMutex.Unlock()
	fake.CreateBuilderEnvironmentStub = nil
	if fake.createBuilderEnvironmentReturnsOnCall == nil {
		fake.createBuilderEnvironmentReturnsOnCall = make(map[int]struct {
			result1 *execution.IsolationContext
			result2 error
		})
	}
	fake.createBuilderEnvironmentReturnsOnCall[i] = struct {
		result1 *execution.IsolationContext
		result2 error
	}{result1, result2}
}

func (fake *FakeIsolationManager) CreateIsolatedEnvironment(arg1 string) (*execution.IsolationContext, error) {
	fake.createIsolatedEnvironmentMutex.Lock()
	ret, specificReturn := fake.createIsolatedEnvironmentReturnsOnCall[len(fake.createIsolatedEnvironmentArgsForCall)]
	fake.createIsolatedEnvironmentArgsForCall = append(fake.createIsolatedEnvironmentArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.CreateIsolatedEnvironmentStub
	fakeReturns := fake.createIsolatedEnvironmentReturns
	fake.recordInvocation("CreateIsolatedEnvironment", []interface{}{arg1})
	fake.createIsolatedEnvironmentMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeIsolationManager) CreateIsolatedEnvironmentCallCount() int {
	fake.createIsolatedEnvironmentMutex.RLock()
	defer fake.createIsolatedEnvironmentMutex.RUnlock()
	return len(fake.createIsolatedEnvironmentArgsForCall)
}

func (fake *FakeIsolationManager) CreateIsolatedEnvironmentCalls(stub func(string) (*execution.IsolationContext, error)) {
	fake.createIsolatedEnvironmentMutex.Lock()
	defer fake.createIsolatedEnvironmentMutex.Unlock()
	fake.CreateIsolatedEnvironmentStub = stub
}

func (fake *FakeIsolationManager) CreateIsolatedEnvironmentArgsForCall(i int) string {
	fake.createIsolatedEnvironmentMutex.RLock()
	defer fake.createIsolatedEnvironmentMutex.RUnlock()
	argsForCall := fake.createIsolatedEnvironmentArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeIsolationManager) CreateIsolatedEnvironmentReturns(result1 *execution.IsolationContext, result2 error) {
	fake.createIsolatedEnvironmentMutex.Lock()
	defer fake.createIsolatedEnvironmentMutex.Unlock()
	fake.CreateIsolatedEnvironmentStub = nil
	fake.createIsolatedEnvironmentReturns = struct {
		result1 *execution.IsolationContext
		result2 error
	}{result1, result2}
}

func (fake *FakeIsolationManager) CreateIsolatedEnvironmentReturnsOnCall(i int, result1 *execution.IsolationContext, result2 error) {
	fake.createIsolatedEnvironmentMutex.Lock()
	defer fake.createIsolatedEnvironmentMutex.Unlock()
	fake.CreateIsolatedEnvironmentStub = nil
	if fake.createIsolatedEnvironmentReturnsOnCall == nil {
		fake.createIsolatedEnvironmentReturnsOnCall = make(map[int]struct {
			result1 *execution.IsolationContext
			result2 error
		})
	}
	fake.createIsolatedEnvironmentReturnsOnCall[i] = struct {
		result1 *execution.IsolationContext
		result2 error
	}{result1, result2}
}

func (fake *FakeIsolationManager) DestroyIsolatedEnvironment(arg1 string) error {
	fake.destroyIsolatedEnvironmentMutex.Lock()
	ret, specificReturn := fake.destroyIsolatedEnvironmentReturnsOnCall[len(fake.destroyIsolatedEnvironmentArgsForCall)]
	fake.destroyIsolatedEnvironmentArgsForCall = append(fake.destroyIsolatedEnvironmentArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.DestroyIsolatedEnvironmentStub
	fakeReturns := fake.destroyIsolatedEnvironmentReturns
	fake.recordInvocation("DestroyIsolatedEnvironment", []interface{}{arg1})
	fake.destroyIsolatedEnvironmentMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeIsolationManager) DestroyIsolatedEnvironmentCallCount() int {
	fake.destroyIsolatedEnvironmentMutex.RLock()
	defer fake.destroyIsolatedEnvironmentMutex.RUnlock()
	return len(fake.destroyIsolatedEnvironmentArgsForCall)
}

func (fake *FakeIsolationManager) DestroyIsolatedEnvironmentCalls(stub func(string) error) {
	fake.destroyIsolatedEnvironmentMutex.Lock()
	defer fake.destroyIsolatedEnvironmentMutex.Unlock()
	fake.DestroyIsolatedEnvironmentStub = stub
}

func (fake *FakeIsolationManager) DestroyIsolatedEnvironmentArgsForCall(i int) string {
	fake.destroyIsolatedEnvironmentMutex.RLock()
	defer fake.destroyIsolatedEnvironmentMutex.RUnlock()
	argsForCall := fake.destroyIsolatedEnvironmentArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeIsolationManager) DestroyIsolatedEnvironmentReturns(result1 error) {
	fake.destroyIsolatedEnvironmentMutex.Lock()
	defer fake.destroyIsolatedEnvironmentMutex.Unlock()
	fake.DestroyIsolatedEnvironmentStub = nil
	fake.destroyIsolatedEnvironmentReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeIsolationManager) DestroyIsolatedEnvironmentReturnsOnCall(i int, result1 error) {
	fake.destroyIsolatedEnvironmentMutex.Lock()
	defer fake.destroyIsolatedEnvironmentMutex.Unlock()
	fake.DestroyIsolatedEnvironmentStub = nil
	if fake.destroyIsolatedEnvironmentReturnsOnCall == nil {
		fake.destroyIsolatedEnvironmentReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.destroyIsolatedEnvironmentReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeIsolationManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeIsolationManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ execution.IsolationManager = new(FakeIsolationManager)
