version: "1.0"

# Java Microservices Configuration
defaults:
  runtime: "java:17"
  network: "backend"
  resources:
    max_memory: 1024
    max_cpu: 50

jobs:
  # API Gateway Service
  api-gateway:
    name: "API Gateway"
    description: "Spring Cloud Gateway service"
    command: java
    args:
      - "-jar"
      - "api-gateway.jar"
      - "--spring.profiles.active=production"
    uploads:
      files:
        - "api-gateway.jar"
        - "application.yml"
    volumes:
      - "config"
      - "logs"
    network: "frontend"
    resources:
      max_memory: 512
      max_cpu: 40

  # User Service
  user-service:
    name: "User Service"
    description: "User management microservice"
    command: java
    args:
      - "-Xmx768m"
      - "-jar"
      - "user-service.jar"
    uploads:
      files:
        - "user-service.jar"
    volumes:
      - "user-data"
      - "logs"
    resources:
      max_memory: 1024

  # Order Service
  order-service:
    name: "Order Service"
    description: "Order processing microservice"
    command: java
    args:
      - "-Xmx768m"
      - "-jar"
      - "order-service.jar"
    uploads:
      files:
        - "order-service.jar"
    volumes:
      - "order-data"
      - "logs"
    resources:
      max_memory: 1024

  # Payment Service with higher resources
  payment-service:
    name: "Payment Service"
    description: "Payment processing microservice"
    command: java
    args:
      - "-Xmx1536m"
      - "-XX:+UseG1GC"
      - "-jar"
      - "payment-service.jar"
    uploads:
      files:
        - "payment-service.jar"
        - "payment-config.properties"
    volumes:
      - "payment-data"
      - "logs"
      - "secure-keys"
    resources:
      max_memory: 2048
      max_cpu: 75
      max_iobps: 2097152  # 2MB/s I/O

  # Database migration job
  db-migration:
    name: "Database Migration"
    description: "Run Flyway database migrations"
    command: java
    args:
      - "-jar"
      - "flyway.jar"
      - "migrate"
      - "-url=jdbc:postgresql://db:5432/myapp"
      - "-schemas=public"
    uploads:
      files:
        - "flyway.jar"
        - "migrations/"
    network: "database"
    resources:
      max_memory: 256

  # Batch processing job
  batch-processor:
    name: "Batch Processor"
    description: "Spring Batch job for data processing"
    command: java
    args:
      - "-Xmx2g"
      - "-jar"
      - "batch-processor.jar"
      - "--job.name=dailyReport"
    uploads:
      files:
        - "batch-processor.jar"
    volumes:
      - "batch-input"
      - "batch-output"
      - "logs"
    schedule: "24hour"
    resources:
      max_memory: 3072
      max_cpu: 90
    runtime: "java:21"  # Use newer Java for better performance