// Code generated by counterfeiter. DO NOT EDIT.
package validationfakes

import (
	"joblet/internal/joblet/core/validation"
	"sync"
)

type FakeRuntimeManagerInterface struct {
	ListRuntimesStub        func() []validation.RuntimeInfo
	listRuntimesMutex       sync.RWMutex
	listRuntimesArgsForCall []struct {
	}
	listRuntimesReturns struct {
		result1 []validation.RuntimeInfo
	}
	listRuntimesReturnsOnCall map[int]struct {
		result1 []validation.RuntimeInfo
	}
	RuntimeExistsStub        func(string) bool
	runtimeExistsMutex       sync.RWMutex
	runtimeExistsArgsForCall []struct {
		arg1 string
	}
	runtimeExistsReturns struct {
		result1 bool
	}
	runtimeExistsReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRuntimeManagerInterface) ListRuntimes() []validation.RuntimeInfo {
	fake.listRuntimesMutex.Lock()
	ret, specificReturn := fake.listRuntimesReturnsOnCall[len(fake.listRuntimesArgsForCall)]
	fake.listRuntimesArgsForCall = append(fake.listRuntimesArgsForCall, struct {
	}{})
	stub := fake.ListRuntimesStub
	fakeReturns := fake.listRuntimesReturns
	fake.recordInvocation("ListRuntimes", []interface{}{})
	fake.listRuntimesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRuntimeManagerInterface) ListRuntimesCallCount() int {
	fake.listRuntimesMutex.RLock()
	defer fake.listRuntimesMutex.RUnlock()
	return len(fake.listRuntimesArgsForCall)
}

func (fake *FakeRuntimeManagerInterface) ListRuntimesCalls(stub func() []validation.RuntimeInfo) {
	fake.listRuntimesMutex.Lock()
	defer fake.listRuntimesMutex.Unlock()
	fake.ListRuntimesStub = stub
}

func (fake *FakeRuntimeManagerInterface) ListRuntimesReturns(result1 []validation.RuntimeInfo) {
	fake.listRuntimesMutex.Lock()
	defer fake.listRuntimesMutex.Unlock()
	fake.ListRuntimesStub = nil
	fake.listRuntimesReturns = struct {
		result1 []validation.RuntimeInfo
	}{result1}
}

func (fake *FakeRuntimeManagerInterface) ListRuntimesReturnsOnCall(i int, result1 []validation.RuntimeInfo) {
	fake.listRuntimesMutex.Lock()
	defer fake.listRuntimesMutex.Unlock()
	fake.ListRuntimesStub = nil
	if fake.listRuntimesReturnsOnCall == nil {
		fake.listRuntimesReturnsOnCall = make(map[int]struct {
			result1 []validation.RuntimeInfo
		})
	}
	fake.listRuntimesReturnsOnCall[i] = struct {
		result1 []validation.RuntimeInfo
	}{result1}
}

func (fake *FakeRuntimeManagerInterface) RuntimeExists(arg1 string) bool {
	fake.runtimeExistsMutex.Lock()
	ret, specificReturn := fake.runtimeExistsReturnsOnCall[len(fake.runtimeExistsArgsForCall)]
	fake.runtimeExistsArgsForCall = append(fake.runtimeExistsArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.RuntimeExistsStub
	fakeReturns := fake.runtimeExistsReturns
	fake.recordInvocation("RuntimeExists", []interface{}{arg1})
	fake.runtimeExistsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRuntimeManagerInterface) RuntimeExistsCallCount() int {
	fake.runtimeExistsMutex.RLock()
	defer fake.runtimeExistsMutex.RUnlock()
	return len(fake.runtimeExistsArgsForCall)
}

func (fake *FakeRuntimeManagerInterface) RuntimeExistsCalls(stub func(string) bool) {
	fake.runtimeExistsMutex.Lock()
	defer fake.runtimeExistsMutex.Unlock()
	fake.RuntimeExistsStub = stub
}

func (fake *FakeRuntimeManagerInterface) RuntimeExistsArgsForCall(i int) string {
	fake.runtimeExistsMutex.RLock()
	defer fake.runtimeExistsMutex.RUnlock()
	argsForCall := fake.runtimeExistsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeRuntimeManagerInterface) RuntimeExistsReturns(result1 bool) {
	fake.runtimeExistsMutex.Lock()
	defer fake.runtimeExistsMutex.Unlock()
	fake.RuntimeExistsStub = nil
	fake.runtimeExistsReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeRuntimeManagerInterface) RuntimeExistsReturnsOnCall(i int, result1 bool) {
	fake.runtimeExistsMutex.Lock()
	defer fake.runtimeExistsMutex.Unlock()
	fake.RuntimeExistsStub = nil
	if fake.runtimeExistsReturnsOnCall == nil {
		fake.runtimeExistsReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.runtimeExistsReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeRuntimeManagerInterface) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRuntimeManagerInterface) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ validation.RuntimeManagerInterface = new(FakeRuntimeManagerInterface)
