// Code generated by counterfeiter. DO NOT EDIT.
package validationfakes

import (
	"joblet/internal/joblet/core/validation"
	"sync"
)

type FakeVolumeManagerInterface struct {
	VolumeExistsStub        func(string) bool
	volumeExistsMutex       sync.RWMutex
	volumeExistsArgsForCall []struct {
		arg1 string
	}
	volumeExistsReturns struct {
		result1 bool
	}
	volumeExistsReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeVolumeManagerInterface) VolumeExists(arg1 string) bool {
	fake.volumeExistsMutex.Lock()
	ret, specificReturn := fake.volumeExistsReturnsOnCall[len(fake.volumeExistsArgsForCall)]
	fake.volumeExistsArgsForCall = append(fake.volumeExistsArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.VolumeExistsStub
	fakeReturns := fake.volumeExistsReturns
	fake.recordInvocation("VolumeExists", []interface{}{arg1})
	fake.volumeExistsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeVolumeManagerInterface) VolumeExistsCallCount() int {
	fake.volumeExistsMutex.RLock()
	defer fake.volumeExistsMutex.RUnlock()
	return len(fake.volumeExistsArgsForCall)
}

func (fake *FakeVolumeManagerInterface) VolumeExistsCalls(stub func(string) bool) {
	fake.volumeExistsMutex.Lock()
	defer fake.volumeExistsMutex.Unlock()
	fake.VolumeExistsStub = stub
}

func (fake *FakeVolumeManagerInterface) VolumeExistsArgsForCall(i int) string {
	fake.volumeExistsMutex.RLock()
	defer fake.volumeExistsMutex.RUnlock()
	argsForCall := fake.volumeExistsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeVolumeManagerInterface) VolumeExistsReturns(result1 bool) {
	fake.volumeExistsMutex.Lock()
	defer fake.volumeExistsMutex.Unlock()
	fake.VolumeExistsStub = nil
	fake.volumeExistsReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeVolumeManagerInterface) VolumeExistsReturnsOnCall(i int, result1 bool) {
	fake.volumeExistsMutex.Lock()
	defer fake.volumeExistsMutex.Unlock()
	fake.VolumeExistsStub = nil
	if fake.volumeExistsReturnsOnCall == nil {
		fake.volumeExistsReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.volumeExistsReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeVolumeManagerInterface) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeVolumeManagerInterface) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ validation.VolumeManagerInterface = new(FakeVolumeManagerInterface)
