// Code generated by counterfeiter. DO NOT EDIT.
package validationfakes

import (
	"joblet/internal/joblet/core/validation"
	"sync"
)

type FakeVolumeValidator struct {
	ListVolumesStub        func() []validation.VolumeInfo
	listVolumesMutex       sync.RWMutex
	listVolumesArgsForCall []struct {
	}
	listVolumesReturns struct {
		result1 []validation.VolumeInfo
	}
	listVolumesReturnsOnCall map[int]struct {
		result1 []validation.VolumeInfo
	}
	ValidateVolumeAccessStub        func(string, bool) error
	validateVolumeAccessMutex       sync.RWMutex
	validateVolumeAccessArgsForCall []struct {
		arg1 string
		arg2 bool
	}
	validateVolumeAccessReturns struct {
		result1 error
	}
	validateVolumeAccessReturnsOnCall map[int]struct {
		result1 error
	}
	VolumeExistsStub        func(string) bool
	volumeExistsMutex       sync.RWMutex
	volumeExistsArgsForCall []struct {
		arg1 string
	}
	volumeExistsReturns struct {
		result1 bool
	}
	volumeExistsReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeVolumeValidator) ListVolumes() []validation.VolumeInfo {
	fake.listVolumesMutex.Lock()
	ret, specificReturn := fake.listVolumesReturnsOnCall[len(fake.listVolumesArgsForCall)]
	fake.listVolumesArgsForCall = append(fake.listVolumesArgsForCall, struct {
	}{})
	stub := fake.ListVolumesStub
	fakeReturns := fake.listVolumesReturns
	fake.recordInvocation("ListVolumes", []interface{}{})
	fake.listVolumesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeVolumeValidator) ListVolumesCallCount() int {
	fake.listVolumesMutex.RLock()
	defer fake.listVolumesMutex.RUnlock()
	return len(fake.listVolumesArgsForCall)
}

func (fake *FakeVolumeValidator) ListVolumesCalls(stub func() []validation.VolumeInfo) {
	fake.listVolumesMutex.Lock()
	defer fake.listVolumesMutex.Unlock()
	fake.ListVolumesStub = stub
}

func (fake *FakeVolumeValidator) ListVolumesReturns(result1 []validation.VolumeInfo) {
	fake.listVolumesMutex.Lock()
	defer fake.listVolumesMutex.Unlock()
	fake.ListVolumesStub = nil
	fake.listVolumesReturns = struct {
		result1 []validation.VolumeInfo
	}{result1}
}

func (fake *FakeVolumeValidator) ListVolumesReturnsOnCall(i int, result1 []validation.VolumeInfo) {
	fake.listVolumesMutex.Lock()
	defer fake.listVolumesMutex.Unlock()
	fake.ListVolumesStub = nil
	if fake.listVolumesReturnsOnCall == nil {
		fake.listVolumesReturnsOnCall = make(map[int]struct {
			result1 []validation.VolumeInfo
		})
	}
	fake.listVolumesReturnsOnCall[i] = struct {
		result1 []validation.VolumeInfo
	}{result1}
}

func (fake *FakeVolumeValidator) ValidateVolumeAccess(arg1 string, arg2 bool) error {
	fake.validateVolumeAccessMutex.Lock()
	ret, specificReturn := fake.validateVolumeAccessReturnsOnCall[len(fake.validateVolumeAccessArgsForCall)]
	fake.validateVolumeAccessArgsForCall = append(fake.validateVolumeAccessArgsForCall, struct {
		arg1 string
		arg2 bool
	}{arg1, arg2})
	stub := fake.ValidateVolumeAccessStub
	fakeReturns := fake.validateVolumeAccessReturns
	fake.recordInvocation("ValidateVolumeAccess", []interface{}{arg1, arg2})
	fake.validateVolumeAccessMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeVolumeValidator) ValidateVolumeAccessCallCount() int {
	fake.validateVolumeAccessMutex.RLock()
	defer fake.validateVolumeAccessMutex.RUnlock()
	return len(fake.validateVolumeAccessArgsForCall)
}

func (fake *FakeVolumeValidator) ValidateVolumeAccessCalls(stub func(string, bool) error) {
	fake.validateVolumeAccessMutex.Lock()
	defer fake.validateVolumeAccessMutex.Unlock()
	fake.ValidateVolumeAccessStub = stub
}

func (fake *FakeVolumeValidator) ValidateVolumeAccessArgsForCall(i int) (string, bool) {
	fake.validateVolumeAccessMutex.RLock()
	defer fake.validateVolumeAccessMutex.RUnlock()
	argsForCall := fake.validateVolumeAccessArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeVolumeValidator) ValidateVolumeAccessReturns(result1 error) {
	fake.validateVolumeAccessMutex.Lock()
	defer fake.validateVolumeAccessMutex.Unlock()
	fake.ValidateVolumeAccessStub = nil
	fake.validateVolumeAccessReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeVolumeValidator) ValidateVolumeAccessReturnsOnCall(i int, result1 error) {
	fake.validateVolumeAccessMutex.Lock()
	defer fake.validateVolumeAccessMutex.Unlock()
	fake.ValidateVolumeAccessStub = nil
	if fake.validateVolumeAccessReturnsOnCall == nil {
		fake.validateVolumeAccessReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateVolumeAccessReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeVolumeValidator) VolumeExists(arg1 string) bool {
	fake.volumeExistsMutex.Lock()
	ret, specificReturn := fake.volumeExistsReturnsOnCall[len(fake.volumeExistsArgsForCall)]
	fake.volumeExistsArgsForCall = append(fake.volumeExistsArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.VolumeExistsStub
	fakeReturns := fake.volumeExistsReturns
	fake.recordInvocation("VolumeExists", []interface{}{arg1})
	fake.volumeExistsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeVolumeValidator) VolumeExistsCallCount() int {
	fake.volumeExistsMutex.RLock()
	defer fake.volumeExistsMutex.RUnlock()
	return len(fake.volumeExistsArgsForCall)
}

func (fake *FakeVolumeValidator) VolumeExistsCalls(stub func(string) bool) {
	fake.volumeExistsMutex.Lock()
	defer fake.volumeExistsMutex.Unlock()
	fake.VolumeExistsStub = stub
}

func (fake *FakeVolumeValidator) VolumeExistsArgsForCall(i int) string {
	fake.volumeExistsMutex.RLock()
	defer fake.volumeExistsMutex.RUnlock()
	argsForCall := fake.volumeExistsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeVolumeValidator) VolumeExistsReturns(result1 bool) {
	fake.volumeExistsMutex.Lock()
	defer fake.volumeExistsMutex.Unlock()
	fake.VolumeExistsStub = nil
	fake.volumeExistsReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeVolumeValidator) VolumeExistsReturnsOnCall(i int, result1 bool) {
	fake.volumeExistsMutex.Lock()
	defer fake.volumeExistsMutex.Unlock()
	fake.VolumeExistsStub = nil
	if fake.volumeExistsReturnsOnCall == nil {
		fake.volumeExistsReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.volumeExistsReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeVolumeValidator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeVolumeValidator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ validation.VolumeValidator = new(FakeVolumeValidator)
