version: "1.0"

# Java 17 Examples - Modern Java Development
defaults:
  runtime: "java:17"
  resources:
    max_memory: 1024
    max_cpu: 50

jobs:
  # Compile and run HelloJoblet
  hello-joblet:
    name: "Hello Joblet Java"
    description: "Compile and run a simple Java application"
    command: bash
    args:
      - "-c"
      - |
        echo "Compiling Java application..."
        javac HelloJoblet.java
        echo "Running Java application..."
        java HelloJoblet
    uploads:
      files:
        - "HelloJoblet.java"
    resources:
      max_memory: 512

  # Run with JVM tuning
  optimized-jvm:
    name: "JVM Optimized Run"
    description: "Run Java with optimized JVM settings"
    command: bash
    args:
      - "-c"
      - |
        javac HelloJoblet.java
        echo "Running with optimized JVM settings..."
        java -Xms256m -Xmx512m -XX:+UseG1GC -XX:MaxGCPauseMillis=100 HelloJoblet
    uploads:
      files:
        - "HelloJoblet.java"
    resources:
      max_memory: 768

  # Text blocks and pattern matching demo (Java 17 features)
  java17-features:
    name: "Java 17 Features Demo"
    description: "Demonstrate Java 17 language features"
    command: bash
    args:
      - "-c"
      - |
        echo "Compiling Java 17 features demo..."
        javac Java17Features.java
        echo "Running Java 17 features demo..."
        java Java17Features
    uploads:
      files:
        - "Java17Features.java"
    resources:
      max_memory: 512

  # JAR packaging and execution
  jar-package:
    name: "JAR Packaging"
    description: "Package Java application as JAR and run"
    command: bash
    args:
      - "-c"
      - |
        echo "Compiling HelloJoblet..."
        javac HelloJoblet.java
        
        echo "Creating manifest..."
        printf "Main-Class: HelloJoblet\n" > manifest.txt
        
        echo "Creating JAR..."
        jar cfm app.jar manifest.txt HelloJoblet.class
        
        echo "Running JAR..."
        java -jar app.jar
    uploads:
      files:
        - "HelloJoblet.java"
    resources:
      max_memory: 512

  # Memory and performance testing using HelloJoblet with arguments
  performance-test:
    name: "Performance Test"
    description: "Test Java application performance with resource limits"
    command: bash
    args:
      - "-c"
      - |
        echo "Compiling and running performance test..."
        javac HelloJoblet.java
        echo "\n=== Performance Test with JVM Options ==="
        java -Xms256m -Xmx768m -XX:+PrintGC HelloJoblet performance-test
    uploads:
      files:
        - "HelloJoblet.java"
    resources:
      max_memory: 1024
      max_cpu: 75

  # Simple compilation test
  compile-test:
    name: "Compilation Test"
    description: "Test compilation of multiple Java files"
    command: bash
    args:
      - "-c"
      - |
        echo "Compiling all Java files..."
        javac *.java
        echo "Running HelloJoblet..."
        java HelloJoblet compile-test
        echo "Running Java17Features..."
        java Java17Features
    uploads:
      files:
        - "HelloJoblet.java"
        - "Java17Features.java"
    resources:
      max_memory: 512