// Code generated by counterfeiter. DO NOT EDIT.
package gpufakes

import (
	"joblet/internal/joblet/gpu"
	"sync"
)

type FakeCUDADetectorInterface struct {
	DetectCUDAStub        func() ([]string, error)
	detectCUDAMutex       sync.RWMutex
	detectCUDAArgsForCall []struct {
	}
	detectCUDAReturns struct {
		result1 []string
		result2 error
	}
	detectCUDAReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	GetCUDAEnvironmentStub        func(string) map[string]string
	getCUDAEnvironmentMutex       sync.RWMutex
	getCUDAEnvironmentArgsForCall []struct {
		arg1 string
	}
	getCUDAEnvironmentReturns struct {
		result1 map[string]string
	}
	getCUDAEnvironmentReturnsOnCall map[int]struct {
		result1 map[string]string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCUDADetectorInterface) DetectCUDA() ([]string, error) {
	fake.detectCUDAMutex.Lock()
	ret, specificReturn := fake.detectCUDAReturnsOnCall[len(fake.detectCUDAArgsForCall)]
	fake.detectCUDAArgsForCall = append(fake.detectCUDAArgsForCall, struct {
	}{})
	stub := fake.DetectCUDAStub
	fakeReturns := fake.detectCUDAReturns
	fake.recordInvocation("DetectCUDA", []interface{}{})
	fake.detectCUDAMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCUDADetectorInterface) DetectCUDACallCount() int {
	fake.detectCUDAMutex.RLock()
	defer fake.detectCUDAMutex.RUnlock()
	return len(fake.detectCUDAArgsForCall)
}

func (fake *FakeCUDADetectorInterface) DetectCUDACalls(stub func() ([]string, error)) {
	fake.detectCUDAMutex.Lock()
	defer fake.detectCUDAMutex.Unlock()
	fake.DetectCUDAStub = stub
}

func (fake *FakeCUDADetectorInterface) DetectCUDAReturns(result1 []string, result2 error) {
	fake.detectCUDAMutex.Lock()
	defer fake.detectCUDAMutex.Unlock()
	fake.DetectCUDAStub = nil
	fake.detectCUDAReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeCUDADetectorInterface) DetectCUDAReturnsOnCall(i int, result1 []string, result2 error) {
	fake.detectCUDAMutex.Lock()
	defer fake.detectCUDAMutex.Unlock()
	fake.DetectCUDAStub = nil
	if fake.detectCUDAReturnsOnCall == nil {
		fake.detectCUDAReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.detectCUDAReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeCUDADetectorInterface) GetCUDAEnvironment(arg1 string) map[string]string {
	fake.getCUDAEnvironmentMutex.Lock()
	ret, specificReturn := fake.getCUDAEnvironmentReturnsOnCall[len(fake.getCUDAEnvironmentArgsForCall)]
	fake.getCUDAEnvironmentArgsForCall = append(fake.getCUDAEnvironmentArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetCUDAEnvironmentStub
	fakeReturns := fake.getCUDAEnvironmentReturns
	fake.recordInvocation("GetCUDAEnvironment", []interface{}{arg1})
	fake.getCUDAEnvironmentMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCUDADetectorInterface) GetCUDAEnvironmentCallCount() int {
	fake.getCUDAEnvironmentMutex.RLock()
	defer fake.getCUDAEnvironmentMutex.RUnlock()
	return len(fake.getCUDAEnvironmentArgsForCall)
}

func (fake *FakeCUDADetectorInterface) GetCUDAEnvironmentCalls(stub func(string) map[string]string) {
	fake.getCUDAEnvironmentMutex.Lock()
	defer fake.getCUDAEnvironmentMutex.Unlock()
	fake.GetCUDAEnvironmentStub = stub
}

func (fake *FakeCUDADetectorInterface) GetCUDAEnvironmentArgsForCall(i int) string {
	fake.getCUDAEnvironmentMutex.RLock()
	defer fake.getCUDAEnvironmentMutex.RUnlock()
	argsForCall := fake.getCUDAEnvironmentArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCUDADetectorInterface) GetCUDAEnvironmentReturns(result1 map[string]string) {
	fake.getCUDAEnvironmentMutex.Lock()
	defer fake.getCUDAEnvironmentMutex.Unlock()
	fake.GetCUDAEnvironmentStub = nil
	fake.getCUDAEnvironmentReturns = struct {
		result1 map[string]string
	}{result1}
}

func (fake *FakeCUDADetectorInterface) GetCUDAEnvironmentReturnsOnCall(i int, result1 map[string]string) {
	fake.getCUDAEnvironmentMutex.Lock()
	defer fake.getCUDAEnvironmentMutex.Unlock()
	fake.GetCUDAEnvironmentStub = nil
	if fake.getCUDAEnvironmentReturnsOnCall == nil {
		fake.getCUDAEnvironmentReturnsOnCall = make(map[int]struct {
			result1 map[string]string
		})
	}
	fake.getCUDAEnvironmentReturnsOnCall[i] = struct {
		result1 map[string]string
	}{result1}
}

func (fake *FakeCUDADetectorInterface) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCUDADetectorInterface) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ gpu.CUDADetectorInterface = new(FakeCUDADetectorInterface)
