// Code generated by counterfeiter. DO NOT EDIT.
package adaptersfakes

import (
	"context"
	"joblet/internal/joblet/adapters"
	"joblet/internal/joblet/domain"
	"sync"
)

type FakeJobStoreAdapter struct {
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	CreateNewJobStub        func(*domain.Job)
	createNewJobMutex       sync.RWMutex
	createNewJobArgsForCall []struct {
		arg1 *domain.Job
	}
	DeleteJobStub        func(string) error
	deleteJobMutex       sync.RWMutex
	deleteJobArgsForCall []struct {
		arg1 string
	}
	deleteJobReturns struct {
		result1 error
	}
	deleteJobReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteJobLogsStub        func(string) error
	deleteJobLogsMutex       sync.RWMutex
	deleteJobLogsArgsForCall []struct {
		arg1 string
	}
	deleteJobLogsReturns struct {
		result1 error
	}
	deleteJobLogsReturnsOnCall map[int]struct {
		result1 error
	}
	GetJobStub        func(string) (*domain.Job, bool)
	getJobMutex       sync.RWMutex
	getJobArgsForCall []struct {
		arg1 string
	}
	getJobReturns struct {
		result1 *domain.Job
		result2 bool
	}
	getJobReturnsOnCall map[int]struct {
		result1 *domain.Job
		result2 bool
	}
	GetJobByPrefixStub        func(string) (*domain.Job, bool)
	getJobByPrefixMutex       sync.RWMutex
	getJobByPrefixArgsForCall []struct {
		arg1 string
	}
	getJobByPrefixReturns struct {
		result1 *domain.Job
		result2 bool
	}
	getJobByPrefixReturnsOnCall map[int]struct {
		result1 *domain.Job
		result2 bool
	}
	GetOutputStub        func(string) ([]byte, bool, error)
	getOutputMutex       sync.RWMutex
	getOutputArgsForCall []struct {
		arg1 string
	}
	getOutputReturns struct {
		result1 []byte
		result2 bool
		result3 error
	}
	getOutputReturnsOnCall map[int]struct {
		result1 []byte
		result2 bool
		result3 error
	}
	ListJobsStub        func() []*domain.Job
	listJobsMutex       sync.RWMutex
	listJobsArgsForCall []struct {
	}
	listJobsReturns struct {
		result1 []*domain.Job
	}
	listJobsReturnsOnCall map[int]struct {
		result1 []*domain.Job
	}
	SendUpdatesToClientStub        func(context.Context, string, adapters.DomainStreamer) error
	sendUpdatesToClientMutex       sync.RWMutex
	sendUpdatesToClientArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 adapters.DomainStreamer
	}
	sendUpdatesToClientReturns struct {
		result1 error
	}
	sendUpdatesToClientReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateJobStub        func(*domain.Job)
	updateJobMutex       sync.RWMutex
	updateJobArgsForCall []struct {
		arg1 *domain.Job
	}
	WriteToBufferStub        func(string, []byte)
	writeToBufferMutex       sync.RWMutex
	writeToBufferArgsForCall []struct {
		arg1 string
		arg2 []byte
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeJobStoreAdapter) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeJobStoreAdapter) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeJobStoreAdapter) CloseCalls(stub func() error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakeJobStoreAdapter) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeJobStoreAdapter) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeJobStoreAdapter) CreateNewJob(arg1 *domain.Job) {
	fake.createNewJobMutex.Lock()
	fake.createNewJobArgsForCall = append(fake.createNewJobArgsForCall, struct {
		arg1 *domain.Job
	}{arg1})
	stub := fake.CreateNewJobStub
	fake.recordInvocation("CreateNewJob", []interface{}{arg1})
	fake.createNewJobMutex.Unlock()
	if stub != nil {
		fake.CreateNewJobStub(arg1)
	}
}

func (fake *FakeJobStoreAdapter) CreateNewJobCallCount() int {
	fake.createNewJobMutex.RLock()
	defer fake.createNewJobMutex.RUnlock()
	return len(fake.createNewJobArgsForCall)
}

func (fake *FakeJobStoreAdapter) CreateNewJobCalls(stub func(*domain.Job)) {
	fake.createNewJobMutex.Lock()
	defer fake.createNewJobMutex.Unlock()
	fake.CreateNewJobStub = stub
}

func (fake *FakeJobStoreAdapter) CreateNewJobArgsForCall(i int) *domain.Job {
	fake.createNewJobMutex.RLock()
	defer fake.createNewJobMutex.RUnlock()
	argsForCall := fake.createNewJobArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeJobStoreAdapter) DeleteJob(arg1 string) error {
	fake.deleteJobMutex.Lock()
	ret, specificReturn := fake.deleteJobReturnsOnCall[len(fake.deleteJobArgsForCall)]
	fake.deleteJobArgsForCall = append(fake.deleteJobArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.DeleteJobStub
	fakeReturns := fake.deleteJobReturns
	fake.recordInvocation("DeleteJob", []interface{}{arg1})
	fake.deleteJobMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeJobStoreAdapter) DeleteJobCallCount() int {
	fake.deleteJobMutex.RLock()
	defer fake.deleteJobMutex.RUnlock()
	return len(fake.deleteJobArgsForCall)
}

func (fake *FakeJobStoreAdapter) DeleteJobCalls(stub func(string) error) {
	fake.deleteJobMutex.Lock()
	defer fake.deleteJobMutex.Unlock()
	fake.DeleteJobStub = stub
}

func (fake *FakeJobStoreAdapter) DeleteJobArgsForCall(i int) string {
	fake.deleteJobMutex.RLock()
	defer fake.deleteJobMutex.RUnlock()
	argsForCall := fake.deleteJobArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeJobStoreAdapter) DeleteJobReturns(result1 error) {
	fake.deleteJobMutex.Lock()
	defer fake.deleteJobMutex.Unlock()
	fake.DeleteJobStub = nil
	fake.deleteJobReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeJobStoreAdapter) DeleteJobReturnsOnCall(i int, result1 error) {
	fake.deleteJobMutex.Lock()
	defer fake.deleteJobMutex.Unlock()
	fake.DeleteJobStub = nil
	if fake.deleteJobReturnsOnCall == nil {
		fake.deleteJobReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteJobReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeJobStoreAdapter) DeleteJobLogs(arg1 string) error {
	fake.deleteJobLogsMutex.Lock()
	ret, specificReturn := fake.deleteJobLogsReturnsOnCall[len(fake.deleteJobLogsArgsForCall)]
	fake.deleteJobLogsArgsForCall = append(fake.deleteJobLogsArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.DeleteJobLogsStub
	fakeReturns := fake.deleteJobLogsReturns
	fake.recordInvocation("DeleteJobLogs", []interface{}{arg1})
	fake.deleteJobLogsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeJobStoreAdapter) DeleteJobLogsCallCount() int {
	fake.deleteJobLogsMutex.RLock()
	defer fake.deleteJobLogsMutex.RUnlock()
	return len(fake.deleteJobLogsArgsForCall)
}

func (fake *FakeJobStoreAdapter) DeleteJobLogsCalls(stub func(string) error) {
	fake.deleteJobLogsMutex.Lock()
	defer fake.deleteJobLogsMutex.Unlock()
	fake.DeleteJobLogsStub = stub
}

func (fake *FakeJobStoreAdapter) DeleteJobLogsArgsForCall(i int) string {
	fake.deleteJobLogsMutex.RLock()
	defer fake.deleteJobLogsMutex.RUnlock()
	argsForCall := fake.deleteJobLogsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeJobStoreAdapter) DeleteJobLogsReturns(result1 error) {
	fake.deleteJobLogsMutex.Lock()
	defer fake.deleteJobLogsMutex.Unlock()
	fake.DeleteJobLogsStub = nil
	fake.deleteJobLogsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeJobStoreAdapter) DeleteJobLogsReturnsOnCall(i int, result1 error) {
	fake.deleteJobLogsMutex.Lock()
	defer fake.deleteJobLogsMutex.Unlock()
	fake.DeleteJobLogsStub = nil
	if fake.deleteJobLogsReturnsOnCall == nil {
		fake.deleteJobLogsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteJobLogsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeJobStoreAdapter) GetJob(arg1 string) (*domain.Job, bool) {
	fake.getJobMutex.Lock()
	ret, specificReturn := fake.getJobReturnsOnCall[len(fake.getJobArgsForCall)]
	fake.getJobArgsForCall = append(fake.getJobArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetJobStub
	fakeReturns := fake.getJobReturns
	fake.recordInvocation("GetJob", []interface{}{arg1})
	fake.getJobMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeJobStoreAdapter) GetJobCallCount() int {
	fake.getJobMutex.RLock()
	defer fake.getJobMutex.RUnlock()
	return len(fake.getJobArgsForCall)
}

func (fake *FakeJobStoreAdapter) GetJobCalls(stub func(string) (*domain.Job, bool)) {
	fake.getJobMutex.Lock()
	defer fake.getJobMutex.Unlock()
	fake.GetJobStub = stub
}

func (fake *FakeJobStoreAdapter) GetJobArgsForCall(i int) string {
	fake.getJobMutex.RLock()
	defer fake.getJobMutex.RUnlock()
	argsForCall := fake.getJobArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeJobStoreAdapter) GetJobReturns(result1 *domain.Job, result2 bool) {
	fake.getJobMutex.Lock()
	defer fake.getJobMutex.Unlock()
	fake.GetJobStub = nil
	fake.getJobReturns = struct {
		result1 *domain.Job
		result2 bool
	}{result1, result2}
}

func (fake *FakeJobStoreAdapter) GetJobReturnsOnCall(i int, result1 *domain.Job, result2 bool) {
	fake.getJobMutex.Lock()
	defer fake.getJobMutex.Unlock()
	fake.GetJobStub = nil
	if fake.getJobReturnsOnCall == nil {
		fake.getJobReturnsOnCall = make(map[int]struct {
			result1 *domain.Job
			result2 bool
		})
	}
	fake.getJobReturnsOnCall[i] = struct {
		result1 *domain.Job
		result2 bool
	}{result1, result2}
}

func (fake *FakeJobStoreAdapter) GetJobByPrefix(arg1 string) (*domain.Job, bool) {
	fake.getJobByPrefixMutex.Lock()
	ret, specificReturn := fake.getJobByPrefixReturnsOnCall[len(fake.getJobByPrefixArgsForCall)]
	fake.getJobByPrefixArgsForCall = append(fake.getJobByPrefixArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetJobByPrefixStub
	fakeReturns := fake.getJobByPrefixReturns
	fake.recordInvocation("GetJobByPrefix", []interface{}{arg1})
	fake.getJobByPrefixMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeJobStoreAdapter) GetJobByPrefixCallCount() int {
	fake.getJobByPrefixMutex.RLock()
	defer fake.getJobByPrefixMutex.RUnlock()
	return len(fake.getJobByPrefixArgsForCall)
}

func (fake *FakeJobStoreAdapter) GetJobByPrefixCalls(stub func(string) (*domain.Job, bool)) {
	fake.getJobByPrefixMutex.Lock()
	defer fake.getJobByPrefixMutex.Unlock()
	fake.GetJobByPrefixStub = stub
}

func (fake *FakeJobStoreAdapter) GetJobByPrefixArgsForCall(i int) string {
	fake.getJobByPrefixMutex.RLock()
	defer fake.getJobByPrefixMutex.RUnlock()
	argsForCall := fake.getJobByPrefixArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeJobStoreAdapter) GetJobByPrefixReturns(result1 *domain.Job, result2 bool) {
	fake.getJobByPrefixMutex.Lock()
	defer fake.getJobByPrefixMutex.Unlock()
	fake.GetJobByPrefixStub = nil
	fake.getJobByPrefixReturns = struct {
		result1 *domain.Job
		result2 bool
	}{result1, result2}
}

func (fake *FakeJobStoreAdapter) GetJobByPrefixReturnsOnCall(i int, result1 *domain.Job, result2 bool) {
	fake.getJobByPrefixMutex.Lock()
	defer fake.getJobByPrefixMutex.Unlock()
	fake.GetJobByPrefixStub = nil
	if fake.getJobByPrefixReturnsOnCall == nil {
		fake.getJobByPrefixReturnsOnCall = make(map[int]struct {
			result1 *domain.Job
			result2 bool
		})
	}
	fake.getJobByPrefixReturnsOnCall[i] = struct {
		result1 *domain.Job
		result2 bool
	}{result1, result2}
}

func (fake *FakeJobStoreAdapter) GetOutput(arg1 string) ([]byte, bool, error) {
	fake.getOutputMutex.Lock()
	ret, specificReturn := fake.getOutputReturnsOnCall[len(fake.getOutputArgsForCall)]
	fake.getOutputArgsForCall = append(fake.getOutputArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetOutputStub
	fakeReturns := fake.getOutputReturns
	fake.recordInvocation("GetOutput", []interface{}{arg1})
	fake.getOutputMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeJobStoreAdapter) GetOutputCallCount() int {
	fake.getOutputMutex.RLock()
	defer fake.getOutputMutex.RUnlock()
	return len(fake.getOutputArgsForCall)
}

func (fake *FakeJobStoreAdapter) GetOutputCalls(stub func(string) ([]byte, bool, error)) {
	fake.getOutputMutex.Lock()
	defer fake.getOutputMutex.Unlock()
	fake.GetOutputStub = stub
}

func (fake *FakeJobStoreAdapter) GetOutputArgsForCall(i int) string {
	fake.getOutputMutex.RLock()
	defer fake.getOutputMutex.RUnlock()
	argsForCall := fake.getOutputArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeJobStoreAdapter) GetOutputReturns(result1 []byte, result2 bool, result3 error) {
	fake.getOutputMutex.Lock()
	defer fake.getOutputMutex.Unlock()
	fake.GetOutputStub = nil
	fake.getOutputReturns = struct {
		result1 []byte
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeJobStoreAdapter) GetOutputReturnsOnCall(i int, result1 []byte, result2 bool, result3 error) {
	fake.getOutputMutex.Lock()
	defer fake.getOutputMutex.Unlock()
	fake.GetOutputStub = nil
	if fake.getOutputReturnsOnCall == nil {
		fake.getOutputReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 bool
			result3 error
		})
	}
	fake.getOutputReturnsOnCall[i] = struct {
		result1 []byte
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeJobStoreAdapter) ListJobs() []*domain.Job {
	fake.listJobsMutex.Lock()
	ret, specificReturn := fake.listJobsReturnsOnCall[len(fake.listJobsArgsForCall)]
	fake.listJobsArgsForCall = append(fake.listJobsArgsForCall, struct {
	}{})
	stub := fake.ListJobsStub
	fakeReturns := fake.listJobsReturns
	fake.recordInvocation("ListJobs", []interface{}{})
	fake.listJobsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeJobStoreAdapter) ListJobsCallCount() int {
	fake.listJobsMutex.RLock()
	defer fake.listJobsMutex.RUnlock()
	return len(fake.listJobsArgsForCall)
}

func (fake *FakeJobStoreAdapter) ListJobsCalls(stub func() []*domain.Job) {
	fake.listJobsMutex.Lock()
	defer fake.listJobsMutex.Unlock()
	fake.ListJobsStub = stub
}

func (fake *FakeJobStoreAdapter) ListJobsReturns(result1 []*domain.Job) {
	fake.listJobsMutex.Lock()
	defer fake.listJobsMutex.Unlock()
	fake.ListJobsStub = nil
	fake.listJobsReturns = struct {
		result1 []*domain.Job
	}{result1}
}

func (fake *FakeJobStoreAdapter) ListJobsReturnsOnCall(i int, result1 []*domain.Job) {
	fake.listJobsMutex.Lock()
	defer fake.listJobsMutex.Unlock()
	fake.ListJobsStub = nil
	if fake.listJobsReturnsOnCall == nil {
		fake.listJobsReturnsOnCall = make(map[int]struct {
			result1 []*domain.Job
		})
	}
	fake.listJobsReturnsOnCall[i] = struct {
		result1 []*domain.Job
	}{result1}
}

func (fake *FakeJobStoreAdapter) SendUpdatesToClient(arg1 context.Context, arg2 string, arg3 adapters.DomainStreamer) error {
	fake.sendUpdatesToClientMutex.Lock()
	ret, specificReturn := fake.sendUpdatesToClientReturnsOnCall[len(fake.sendUpdatesToClientArgsForCall)]
	fake.sendUpdatesToClientArgsForCall = append(fake.sendUpdatesToClientArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 adapters.DomainStreamer
	}{arg1, arg2, arg3})
	stub := fake.SendUpdatesToClientStub
	fakeReturns := fake.sendUpdatesToClientReturns
	fake.recordInvocation("SendUpdatesToClient", []interface{}{arg1, arg2, arg3})
	fake.sendUpdatesToClientMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeJobStoreAdapter) SendUpdatesToClientCallCount() int {
	fake.sendUpdatesToClientMutex.RLock()
	defer fake.sendUpdatesToClientMutex.RUnlock()
	return len(fake.sendUpdatesToClientArgsForCall)
}

func (fake *FakeJobStoreAdapter) SendUpdatesToClientCalls(stub func(context.Context, string, adapters.DomainStreamer) error) {
	fake.sendUpdatesToClientMutex.Lock()
	defer fake.sendUpdatesToClientMutex.Unlock()
	fake.SendUpdatesToClientStub = stub
}

func (fake *FakeJobStoreAdapter) SendUpdatesToClientArgsForCall(i int) (context.Context, string, adapters.DomainStreamer) {
	fake.sendUpdatesToClientMutex.RLock()
	defer fake.sendUpdatesToClientMutex.RUnlock()
	argsForCall := fake.sendUpdatesToClientArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeJobStoreAdapter) SendUpdatesToClientReturns(result1 error) {
	fake.sendUpdatesToClientMutex.Lock()
	defer fake.sendUpdatesToClientMutex.Unlock()
	fake.SendUpdatesToClientStub = nil
	fake.sendUpdatesToClientReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeJobStoreAdapter) SendUpdatesToClientReturnsOnCall(i int, result1 error) {
	fake.sendUpdatesToClientMutex.Lock()
	defer fake.sendUpdatesToClientMutex.Unlock()
	fake.SendUpdatesToClientStub = nil
	if fake.sendUpdatesToClientReturnsOnCall == nil {
		fake.sendUpdatesToClientReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.sendUpdatesToClientReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeJobStoreAdapter) UpdateJob(arg1 *domain.Job) {
	fake.updateJobMutex.Lock()
	fake.updateJobArgsForCall = append(fake.updateJobArgsForCall, struct {
		arg1 *domain.Job
	}{arg1})
	stub := fake.UpdateJobStub
	fake.recordInvocation("UpdateJob", []interface{}{arg1})
	fake.updateJobMutex.Unlock()
	if stub != nil {
		fake.UpdateJobStub(arg1)
	}
}

func (fake *FakeJobStoreAdapter) UpdateJobCallCount() int {
	fake.updateJobMutex.RLock()
	defer fake.updateJobMutex.RUnlock()
	return len(fake.updateJobArgsForCall)
}

func (fake *FakeJobStoreAdapter) UpdateJobCalls(stub func(*domain.Job)) {
	fake.updateJobMutex.Lock()
	defer fake.updateJobMutex.Unlock()
	fake.UpdateJobStub = stub
}

func (fake *FakeJobStoreAdapter) UpdateJobArgsForCall(i int) *domain.Job {
	fake.updateJobMutex.RLock()
	defer fake.updateJobMutex.RUnlock()
	argsForCall := fake.updateJobArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeJobStoreAdapter) WriteToBuffer(arg1 string, arg2 []byte) {
	var arg2Copy []byte
	if arg2 != nil {
		arg2Copy = make([]byte, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.writeToBufferMutex.Lock()
	fake.writeToBufferArgsForCall = append(fake.writeToBufferArgsForCall, struct {
		arg1 string
		arg2 []byte
	}{arg1, arg2Copy})
	stub := fake.WriteToBufferStub
	fake.recordInvocation("WriteToBuffer", []interface{}{arg1, arg2Copy})
	fake.writeToBufferMutex.Unlock()
	if stub != nil {
		fake.WriteToBufferStub(arg1, arg2)
	}
}

func (fake *FakeJobStoreAdapter) WriteToBufferCallCount() int {
	fake.writeToBufferMutex.RLock()
	defer fake.writeToBufferMutex.RUnlock()
	return len(fake.writeToBufferArgsForCall)
}

func (fake *FakeJobStoreAdapter) WriteToBufferCalls(stub func(string, []byte)) {
	fake.writeToBufferMutex.Lock()
	defer fake.writeToBufferMutex.Unlock()
	fake.WriteToBufferStub = stub
}

func (fake *FakeJobStoreAdapter) WriteToBufferArgsForCall(i int) (string, []byte) {
	fake.writeToBufferMutex.RLock()
	defer fake.writeToBufferMutex.RUnlock()
	argsForCall := fake.writeToBufferArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeJobStoreAdapter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeJobStoreAdapter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ adapters.JobStoreAdapter = new(FakeJobStoreAdapter)
