// Code generated by counterfeiter. DO NOT EDIT.
package adaptersfakes

import (
	"context"
	"sync"

	"github.com/ehsaniara/joblet/internal/joblet/adapters"
)

type FakeMetricsStorer struct {
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	GetHistoricalMetricsStub        func(string, int64, int64) ([]interface{}, error)
	getHistoricalMetricsMutex       sync.RWMutex
	getHistoricalMetricsArgsForCall []struct {
		arg1 string
		arg2 int64
		arg3 int64
	}
	getHistoricalMetricsReturns struct {
		result1 []interface{}
		result2 error
	}
	getHistoricalMetricsReturnsOnCall map[int]struct {
		result1 []interface{}
		result2 error
	}
	StreamMetricsStub        func(context.Context, string) (<-chan interface{}, error)
	streamMetricsMutex       sync.RWMutex
	streamMetricsArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	streamMetricsReturns struct {
		result1 <-chan interface{}
		result2 error
	}
	streamMetricsReturnsOnCall map[int]struct {
		result1 <-chan interface{}
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMetricsStorer) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMetricsStorer) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeMetricsStorer) CloseCalls(stub func() error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakeMetricsStorer) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMetricsStorer) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMetricsStorer) GetHistoricalMetrics(arg1 string, arg2 int64, arg3 int64) ([]interface{}, error) {
	fake.getHistoricalMetricsMutex.Lock()
	ret, specificReturn := fake.getHistoricalMetricsReturnsOnCall[len(fake.getHistoricalMetricsArgsForCall)]
	fake.getHistoricalMetricsArgsForCall = append(fake.getHistoricalMetricsArgsForCall, struct {
		arg1 string
		arg2 int64
		arg3 int64
	}{arg1, arg2, arg3})
	stub := fake.GetHistoricalMetricsStub
	fakeReturns := fake.getHistoricalMetricsReturns
	fake.recordInvocation("GetHistoricalMetrics", []interface{}{arg1, arg2, arg3})
	fake.getHistoricalMetricsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMetricsStorer) GetHistoricalMetricsCallCount() int {
	fake.getHistoricalMetricsMutex.RLock()
	defer fake.getHistoricalMetricsMutex.RUnlock()
	return len(fake.getHistoricalMetricsArgsForCall)
}

func (fake *FakeMetricsStorer) GetHistoricalMetricsCalls(stub func(string, int64, int64) ([]interface{}, error)) {
	fake.getHistoricalMetricsMutex.Lock()
	defer fake.getHistoricalMetricsMutex.Unlock()
	fake.GetHistoricalMetricsStub = stub
}

func (fake *FakeMetricsStorer) GetHistoricalMetricsArgsForCall(i int) (string, int64, int64) {
	fake.getHistoricalMetricsMutex.RLock()
	defer fake.getHistoricalMetricsMutex.RUnlock()
	argsForCall := fake.getHistoricalMetricsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeMetricsStorer) GetHistoricalMetricsReturns(result1 []interface{}, result2 error) {
	fake.getHistoricalMetricsMutex.Lock()
	defer fake.getHistoricalMetricsMutex.Unlock()
	fake.GetHistoricalMetricsStub = nil
	fake.getHistoricalMetricsReturns = struct {
		result1 []interface{}
		result2 error
	}{result1, result2}
}

func (fake *FakeMetricsStorer) GetHistoricalMetricsReturnsOnCall(i int, result1 []interface{}, result2 error) {
	fake.getHistoricalMetricsMutex.Lock()
	defer fake.getHistoricalMetricsMutex.Unlock()
	fake.GetHistoricalMetricsStub = nil
	if fake.getHistoricalMetricsReturnsOnCall == nil {
		fake.getHistoricalMetricsReturnsOnCall = make(map[int]struct {
			result1 []interface{}
			result2 error
		})
	}
	fake.getHistoricalMetricsReturnsOnCall[i] = struct {
		result1 []interface{}
		result2 error
	}{result1, result2}
}

func (fake *FakeMetricsStorer) StreamMetrics(arg1 context.Context, arg2 string) (<-chan interface{}, error) {
	fake.streamMetricsMutex.Lock()
	ret, specificReturn := fake.streamMetricsReturnsOnCall[len(fake.streamMetricsArgsForCall)]
	fake.streamMetricsArgsForCall = append(fake.streamMetricsArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.StreamMetricsStub
	fakeReturns := fake.streamMetricsReturns
	fake.recordInvocation("StreamMetrics", []interface{}{arg1, arg2})
	fake.streamMetricsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMetricsStorer) StreamMetricsCallCount() int {
	fake.streamMetricsMutex.RLock()
	defer fake.streamMetricsMutex.RUnlock()
	return len(fake.streamMetricsArgsForCall)
}

func (fake *FakeMetricsStorer) StreamMetricsCalls(stub func(context.Context, string) (<-chan interface{}, error)) {
	fake.streamMetricsMutex.Lock()
	defer fake.streamMetricsMutex.Unlock()
	fake.StreamMetricsStub = stub
}

func (fake *FakeMetricsStorer) StreamMetricsArgsForCall(i int) (context.Context, string) {
	fake.streamMetricsMutex.RLock()
	defer fake.streamMetricsMutex.RUnlock()
	argsForCall := fake.streamMetricsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMetricsStorer) StreamMetricsReturns(result1 <-chan interface{}, result2 error) {
	fake.streamMetricsMutex.Lock()
	defer fake.streamMetricsMutex.Unlock()
	fake.StreamMetricsStub = nil
	fake.streamMetricsReturns = struct {
		result1 <-chan interface{}
		result2 error
	}{result1, result2}
}

func (fake *FakeMetricsStorer) StreamMetricsReturnsOnCall(i int, result1 <-chan interface{}, result2 error) {
	fake.streamMetricsMutex.Lock()
	defer fake.streamMetricsMutex.Unlock()
	fake.StreamMetricsStub = nil
	if fake.streamMetricsReturnsOnCall == nil {
		fake.streamMetricsReturnsOnCall = make(map[int]struct {
			result1 <-chan interface{}
			result2 error
		})
	}
	fake.streamMetricsReturnsOnCall[i] = struct {
		result1 <-chan interface{}
		result2 error
	}{result1, result2}
}

func (fake *FakeMetricsStorer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMetricsStorer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ adapters.MetricsStorer = new(FakeMetricsStorer)
