// Code generated by counterfeiter. DO NOT EDIT.
package jobfakes

import (
	"joblet/internal/joblet/core/job"
	"joblet/internal/joblet/domain"
	"sync"
)

type FakeBuildRequest struct {
	GetArgsStub        func() []string
	getArgsMutex       sync.RWMutex
	getArgsArgsForCall []struct {
	}
	getArgsReturns struct {
		result1 []string
	}
	getArgsReturnsOnCall map[int]struct {
		result1 []string
	}
	GetCommandStub        func() string
	getCommandMutex       sync.RWMutex
	getCommandArgsForCall []struct {
	}
	getCommandReturns struct {
		result1 string
	}
	getCommandReturnsOnCall map[int]struct {
		result1 string
	}
	GetEnvironmentStub        func() map[string]string
	getEnvironmentMutex       sync.RWMutex
	getEnvironmentArgsForCall []struct {
	}
	getEnvironmentReturns struct {
		result1 map[string]string
	}
	getEnvironmentReturnsOnCall map[int]struct {
		result1 map[string]string
	}
	GetJobTypeStub        func() domain.JobType
	getJobTypeMutex       sync.RWMutex
	getJobTypeArgsForCall []struct {
	}
	getJobTypeReturns struct {
		result1 domain.JobType
	}
	getJobTypeReturnsOnCall map[int]struct {
		result1 domain.JobType
	}
	GetLimitsStub        func() domain.ResourceLimits
	getLimitsMutex       sync.RWMutex
	getLimitsArgsForCall []struct {
	}
	getLimitsReturns struct {
		result1 domain.ResourceLimits
	}
	getLimitsReturnsOnCall map[int]struct {
		result1 domain.ResourceLimits
	}
	GetNetworkStub        func() string
	getNetworkMutex       sync.RWMutex
	getNetworkArgsForCall []struct {
	}
	getNetworkReturns struct {
		result1 string
	}
	getNetworkReturnsOnCall map[int]struct {
		result1 string
	}
	GetRuntimeStub        func() string
	getRuntimeMutex       sync.RWMutex
	getRuntimeArgsForCall []struct {
	}
	getRuntimeReturns struct {
		result1 string
	}
	getRuntimeReturnsOnCall map[int]struct {
		result1 string
	}
	GetSecretEnvironmentStub        func() map[string]string
	getSecretEnvironmentMutex       sync.RWMutex
	getSecretEnvironmentArgsForCall []struct {
	}
	getSecretEnvironmentReturns struct {
		result1 map[string]string
	}
	getSecretEnvironmentReturnsOnCall map[int]struct {
		result1 map[string]string
	}
	GetVolumesStub        func() []string
	getVolumesMutex       sync.RWMutex
	getVolumesArgsForCall []struct {
	}
	getVolumesReturns struct {
		result1 []string
	}
	getVolumesReturnsOnCall map[int]struct {
		result1 []string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBuildRequest) GetArgs() []string {
	fake.getArgsMutex.Lock()
	ret, specificReturn := fake.getArgsReturnsOnCall[len(fake.getArgsArgsForCall)]
	fake.getArgsArgsForCall = append(fake.getArgsArgsForCall, struct {
	}{})
	stub := fake.GetArgsStub
	fakeReturns := fake.getArgsReturns
	fake.recordInvocation("GetArgs", []interface{}{})
	fake.getArgsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBuildRequest) GetArgsCallCount() int {
	fake.getArgsMutex.RLock()
	defer fake.getArgsMutex.RUnlock()
	return len(fake.getArgsArgsForCall)
}

func (fake *FakeBuildRequest) GetArgsCalls(stub func() []string) {
	fake.getArgsMutex.Lock()
	defer fake.getArgsMutex.Unlock()
	fake.GetArgsStub = stub
}

func (fake *FakeBuildRequest) GetArgsReturns(result1 []string) {
	fake.getArgsMutex.Lock()
	defer fake.getArgsMutex.Unlock()
	fake.GetArgsStub = nil
	fake.getArgsReturns = struct {
		result1 []string
	}{result1}
}

func (fake *FakeBuildRequest) GetArgsReturnsOnCall(i int, result1 []string) {
	fake.getArgsMutex.Lock()
	defer fake.getArgsMutex.Unlock()
	fake.GetArgsStub = nil
	if fake.getArgsReturnsOnCall == nil {
		fake.getArgsReturnsOnCall = make(map[int]struct {
			result1 []string
		})
	}
	fake.getArgsReturnsOnCall[i] = struct {
		result1 []string
	}{result1}
}

func (fake *FakeBuildRequest) GetCommand() string {
	fake.getCommandMutex.Lock()
	ret, specificReturn := fake.getCommandReturnsOnCall[len(fake.getCommandArgsForCall)]
	fake.getCommandArgsForCall = append(fake.getCommandArgsForCall, struct {
	}{})
	stub := fake.GetCommandStub
	fakeReturns := fake.getCommandReturns
	fake.recordInvocation("GetCommand", []interface{}{})
	fake.getCommandMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBuildRequest) GetCommandCallCount() int {
	fake.getCommandMutex.RLock()
	defer fake.getCommandMutex.RUnlock()
	return len(fake.getCommandArgsForCall)
}

func (fake *FakeBuildRequest) GetCommandCalls(stub func() string) {
	fake.getCommandMutex.Lock()
	defer fake.getCommandMutex.Unlock()
	fake.GetCommandStub = stub
}

func (fake *FakeBuildRequest) GetCommandReturns(result1 string) {
	fake.getCommandMutex.Lock()
	defer fake.getCommandMutex.Unlock()
	fake.GetCommandStub = nil
	fake.getCommandReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeBuildRequest) GetCommandReturnsOnCall(i int, result1 string) {
	fake.getCommandMutex.Lock()
	defer fake.getCommandMutex.Unlock()
	fake.GetCommandStub = nil
	if fake.getCommandReturnsOnCall == nil {
		fake.getCommandReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getCommandReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeBuildRequest) GetEnvironment() map[string]string {
	fake.getEnvironmentMutex.Lock()
	ret, specificReturn := fake.getEnvironmentReturnsOnCall[len(fake.getEnvironmentArgsForCall)]
	fake.getEnvironmentArgsForCall = append(fake.getEnvironmentArgsForCall, struct {
	}{})
	stub := fake.GetEnvironmentStub
	fakeReturns := fake.getEnvironmentReturns
	fake.recordInvocation("GetEnvironment", []interface{}{})
	fake.getEnvironmentMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBuildRequest) GetEnvironmentCallCount() int {
	fake.getEnvironmentMutex.RLock()
	defer fake.getEnvironmentMutex.RUnlock()
	return len(fake.getEnvironmentArgsForCall)
}

func (fake *FakeBuildRequest) GetEnvironmentCalls(stub func() map[string]string) {
	fake.getEnvironmentMutex.Lock()
	defer fake.getEnvironmentMutex.Unlock()
	fake.GetEnvironmentStub = stub
}

func (fake *FakeBuildRequest) GetEnvironmentReturns(result1 map[string]string) {
	fake.getEnvironmentMutex.Lock()
	defer fake.getEnvironmentMutex.Unlock()
	fake.GetEnvironmentStub = nil
	fake.getEnvironmentReturns = struct {
		result1 map[string]string
	}{result1}
}

func (fake *FakeBuildRequest) GetEnvironmentReturnsOnCall(i int, result1 map[string]string) {
	fake.getEnvironmentMutex.Lock()
	defer fake.getEnvironmentMutex.Unlock()
	fake.GetEnvironmentStub = nil
	if fake.getEnvironmentReturnsOnCall == nil {
		fake.getEnvironmentReturnsOnCall = make(map[int]struct {
			result1 map[string]string
		})
	}
	fake.getEnvironmentReturnsOnCall[i] = struct {
		result1 map[string]string
	}{result1}
}

func (fake *FakeBuildRequest) GetJobType() domain.JobType {
	fake.getJobTypeMutex.Lock()
	ret, specificReturn := fake.getJobTypeReturnsOnCall[len(fake.getJobTypeArgsForCall)]
	fake.getJobTypeArgsForCall = append(fake.getJobTypeArgsForCall, struct {
	}{})
	stub := fake.GetJobTypeStub
	fakeReturns := fake.getJobTypeReturns
	fake.recordInvocation("GetJobType", []interface{}{})
	fake.getJobTypeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBuildRequest) GetJobTypeCallCount() int {
	fake.getJobTypeMutex.RLock()
	defer fake.getJobTypeMutex.RUnlock()
	return len(fake.getJobTypeArgsForCall)
}

func (fake *FakeBuildRequest) GetJobTypeCalls(stub func() domain.JobType) {
	fake.getJobTypeMutex.Lock()
	defer fake.getJobTypeMutex.Unlock()
	fake.GetJobTypeStub = stub
}

func (fake *FakeBuildRequest) GetJobTypeReturns(result1 domain.JobType) {
	fake.getJobTypeMutex.Lock()
	defer fake.getJobTypeMutex.Unlock()
	fake.GetJobTypeStub = nil
	fake.getJobTypeReturns = struct {
		result1 domain.JobType
	}{result1}
}

func (fake *FakeBuildRequest) GetJobTypeReturnsOnCall(i int, result1 domain.JobType) {
	fake.getJobTypeMutex.Lock()
	defer fake.getJobTypeMutex.Unlock()
	fake.GetJobTypeStub = nil
	if fake.getJobTypeReturnsOnCall == nil {
		fake.getJobTypeReturnsOnCall = make(map[int]struct {
			result1 domain.JobType
		})
	}
	fake.getJobTypeReturnsOnCall[i] = struct {
		result1 domain.JobType
	}{result1}
}

func (fake *FakeBuildRequest) GetLimits() domain.ResourceLimits {
	fake.getLimitsMutex.Lock()
	ret, specificReturn := fake.getLimitsReturnsOnCall[len(fake.getLimitsArgsForCall)]
	fake.getLimitsArgsForCall = append(fake.getLimitsArgsForCall, struct {
	}{})
	stub := fake.GetLimitsStub
	fakeReturns := fake.getLimitsReturns
	fake.recordInvocation("GetLimits", []interface{}{})
	fake.getLimitsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBuildRequest) GetLimitsCallCount() int {
	fake.getLimitsMutex.RLock()
	defer fake.getLimitsMutex.RUnlock()
	return len(fake.getLimitsArgsForCall)
}

func (fake *FakeBuildRequest) GetLimitsCalls(stub func() domain.ResourceLimits) {
	fake.getLimitsMutex.Lock()
	defer fake.getLimitsMutex.Unlock()
	fake.GetLimitsStub = stub
}

func (fake *FakeBuildRequest) GetLimitsReturns(result1 domain.ResourceLimits) {
	fake.getLimitsMutex.Lock()
	defer fake.getLimitsMutex.Unlock()
	fake.GetLimitsStub = nil
	fake.getLimitsReturns = struct {
		result1 domain.ResourceLimits
	}{result1}
}

func (fake *FakeBuildRequest) GetLimitsReturnsOnCall(i int, result1 domain.ResourceLimits) {
	fake.getLimitsMutex.Lock()
	defer fake.getLimitsMutex.Unlock()
	fake.GetLimitsStub = nil
	if fake.getLimitsReturnsOnCall == nil {
		fake.getLimitsReturnsOnCall = make(map[int]struct {
			result1 domain.ResourceLimits
		})
	}
	fake.getLimitsReturnsOnCall[i] = struct {
		result1 domain.ResourceLimits
	}{result1}
}

func (fake *FakeBuildRequest) GetNetwork() string {
	fake.getNetworkMutex.Lock()
	ret, specificReturn := fake.getNetworkReturnsOnCall[len(fake.getNetworkArgsForCall)]
	fake.getNetworkArgsForCall = append(fake.getNetworkArgsForCall, struct {
	}{})
	stub := fake.GetNetworkStub
	fakeReturns := fake.getNetworkReturns
	fake.recordInvocation("GetNetwork", []interface{}{})
	fake.getNetworkMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBuildRequest) GetNetworkCallCount() int {
	fake.getNetworkMutex.RLock()
	defer fake.getNetworkMutex.RUnlock()
	return len(fake.getNetworkArgsForCall)
}

func (fake *FakeBuildRequest) GetNetworkCalls(stub func() string) {
	fake.getNetworkMutex.Lock()
	defer fake.getNetworkMutex.Unlock()
	fake.GetNetworkStub = stub
}

func (fake *FakeBuildRequest) GetNetworkReturns(result1 string) {
	fake.getNetworkMutex.Lock()
	defer fake.getNetworkMutex.Unlock()
	fake.GetNetworkStub = nil
	fake.getNetworkReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeBuildRequest) GetNetworkReturnsOnCall(i int, result1 string) {
	fake.getNetworkMutex.Lock()
	defer fake.getNetworkMutex.Unlock()
	fake.GetNetworkStub = nil
	if fake.getNetworkReturnsOnCall == nil {
		fake.getNetworkReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getNetworkReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeBuildRequest) GetRuntime() string {
	fake.getRuntimeMutex.Lock()
	ret, specificReturn := fake.getRuntimeReturnsOnCall[len(fake.getRuntimeArgsForCall)]
	fake.getRuntimeArgsForCall = append(fake.getRuntimeArgsForCall, struct {
	}{})
	stub := fake.GetRuntimeStub
	fakeReturns := fake.getRuntimeReturns
	fake.recordInvocation("GetRuntime", []interface{}{})
	fake.getRuntimeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBuildRequest) GetRuntimeCallCount() int {
	fake.getRuntimeMutex.RLock()
	defer fake.getRuntimeMutex.RUnlock()
	return len(fake.getRuntimeArgsForCall)
}

func (fake *FakeBuildRequest) GetRuntimeCalls(stub func() string) {
	fake.getRuntimeMutex.Lock()
	defer fake.getRuntimeMutex.Unlock()
	fake.GetRuntimeStub = stub
}

func (fake *FakeBuildRequest) GetRuntimeReturns(result1 string) {
	fake.getRuntimeMutex.Lock()
	defer fake.getRuntimeMutex.Unlock()
	fake.GetRuntimeStub = nil
	fake.getRuntimeReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeBuildRequest) GetRuntimeReturnsOnCall(i int, result1 string) {
	fake.getRuntimeMutex.Lock()
	defer fake.getRuntimeMutex.Unlock()
	fake.GetRuntimeStub = nil
	if fake.getRuntimeReturnsOnCall == nil {
		fake.getRuntimeReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getRuntimeReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeBuildRequest) GetSecretEnvironment() map[string]string {
	fake.getSecretEnvironmentMutex.Lock()
	ret, specificReturn := fake.getSecretEnvironmentReturnsOnCall[len(fake.getSecretEnvironmentArgsForCall)]
	fake.getSecretEnvironmentArgsForCall = append(fake.getSecretEnvironmentArgsForCall, struct {
	}{})
	stub := fake.GetSecretEnvironmentStub
	fakeReturns := fake.getSecretEnvironmentReturns
	fake.recordInvocation("GetSecretEnvironment", []interface{}{})
	fake.getSecretEnvironmentMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBuildRequest) GetSecretEnvironmentCallCount() int {
	fake.getSecretEnvironmentMutex.RLock()
	defer fake.getSecretEnvironmentMutex.RUnlock()
	return len(fake.getSecretEnvironmentArgsForCall)
}

func (fake *FakeBuildRequest) GetSecretEnvironmentCalls(stub func() map[string]string) {
	fake.getSecretEnvironmentMutex.Lock()
	defer fake.getSecretEnvironmentMutex.Unlock()
	fake.GetSecretEnvironmentStub = stub
}

func (fake *FakeBuildRequest) GetSecretEnvironmentReturns(result1 map[string]string) {
	fake.getSecretEnvironmentMutex.Lock()
	defer fake.getSecretEnvironmentMutex.Unlock()
	fake.GetSecretEnvironmentStub = nil
	fake.getSecretEnvironmentReturns = struct {
		result1 map[string]string
	}{result1}
}

func (fake *FakeBuildRequest) GetSecretEnvironmentReturnsOnCall(i int, result1 map[string]string) {
	fake.getSecretEnvironmentMutex.Lock()
	defer fake.getSecretEnvironmentMutex.Unlock()
	fake.GetSecretEnvironmentStub = nil
	if fake.getSecretEnvironmentReturnsOnCall == nil {
		fake.getSecretEnvironmentReturnsOnCall = make(map[int]struct {
			result1 map[string]string
		})
	}
	fake.getSecretEnvironmentReturnsOnCall[i] = struct {
		result1 map[string]string
	}{result1}
}

func (fake *FakeBuildRequest) GetVolumes() []string {
	fake.getVolumesMutex.Lock()
	ret, specificReturn := fake.getVolumesReturnsOnCall[len(fake.getVolumesArgsForCall)]
	fake.getVolumesArgsForCall = append(fake.getVolumesArgsForCall, struct {
	}{})
	stub := fake.GetVolumesStub
	fakeReturns := fake.getVolumesReturns
	fake.recordInvocation("GetVolumes", []interface{}{})
	fake.getVolumesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBuildRequest) GetVolumesCallCount() int {
	fake.getVolumesMutex.RLock()
	defer fake.getVolumesMutex.RUnlock()
	return len(fake.getVolumesArgsForCall)
}

func (fake *FakeBuildRequest) GetVolumesCalls(stub func() []string) {
	fake.getVolumesMutex.Lock()
	defer fake.getVolumesMutex.Unlock()
	fake.GetVolumesStub = stub
}

func (fake *FakeBuildRequest) GetVolumesReturns(result1 []string) {
	fake.getVolumesMutex.Lock()
	defer fake.getVolumesMutex.Unlock()
	fake.GetVolumesStub = nil
	fake.getVolumesReturns = struct {
		result1 []string
	}{result1}
}

func (fake *FakeBuildRequest) GetVolumesReturnsOnCall(i int, result1 []string) {
	fake.getVolumesMutex.Lock()
	defer fake.getVolumesMutex.Unlock()
	fake.GetVolumesStub = nil
	if fake.getVolumesReturnsOnCall == nil {
		fake.getVolumesReturnsOnCall = make(map[int]struct {
			result1 []string
		})
	}
	fake.getVolumesReturnsOnCall[i] = struct {
		result1 []string
	}{result1}
}

func (fake *FakeBuildRequest) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBuildRequest) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ job.BuildRequest = new(FakeBuildRequest)
