// Code generated by counterfeiter. DO NOT EDIT.
package networkfakes

import (
	"sync"

	"github.com/ehsaniara/joblet/internal/joblet/network"
)

type FakeNetworkStoreInterface struct {
	GetNetworkConfigStub        func(string) (*network.NetworkConfig, error)
	getNetworkConfigMutex       sync.RWMutex
	getNetworkConfigArgsForCall []struct {
		arg1 string
	}
	getNetworkConfigReturns struct {
		result1 *network.NetworkConfig
		result2 error
	}
	getNetworkConfigReturnsOnCall map[int]struct {
		result1 *network.NetworkConfig
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeNetworkStoreInterface) GetNetworkConfig(arg1 string) (*network.NetworkConfig, error) {
	fake.getNetworkConfigMutex.Lock()
	ret, specificReturn := fake.getNetworkConfigReturnsOnCall[len(fake.getNetworkConfigArgsForCall)]
	fake.getNetworkConfigArgsForCall = append(fake.getNetworkConfigArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetNetworkConfigStub
	fakeReturns := fake.getNetworkConfigReturns
	fake.recordInvocation("GetNetworkConfig", []interface{}{arg1})
	fake.getNetworkConfigMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeNetworkStoreInterface) GetNetworkConfigCallCount() int {
	fake.getNetworkConfigMutex.RLock()
	defer fake.getNetworkConfigMutex.RUnlock()
	return len(fake.getNetworkConfigArgsForCall)
}

func (fake *FakeNetworkStoreInterface) GetNetworkConfigCalls(stub func(string) (*network.NetworkConfig, error)) {
	fake.getNetworkConfigMutex.Lock()
	defer fake.getNetworkConfigMutex.Unlock()
	fake.GetNetworkConfigStub = stub
}

func (fake *FakeNetworkStoreInterface) GetNetworkConfigArgsForCall(i int) string {
	fake.getNetworkConfigMutex.RLock()
	defer fake.getNetworkConfigMutex.RUnlock()
	argsForCall := fake.getNetworkConfigArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeNetworkStoreInterface) GetNetworkConfigReturns(result1 *network.NetworkConfig, result2 error) {
	fake.getNetworkConfigMutex.Lock()
	defer fake.getNetworkConfigMutex.Unlock()
	fake.GetNetworkConfigStub = nil
	fake.getNetworkConfigReturns = struct {
		result1 *network.NetworkConfig
		result2 error
	}{result1, result2}
}

func (fake *FakeNetworkStoreInterface) GetNetworkConfigReturnsOnCall(i int, result1 *network.NetworkConfig, result2 error) {
	fake.getNetworkConfigMutex.Lock()
	defer fake.getNetworkConfigMutex.Unlock()
	fake.GetNetworkConfigStub = nil
	if fake.getNetworkConfigReturnsOnCall == nil {
		fake.getNetworkConfigReturnsOnCall = make(map[int]struct {
			result1 *network.NetworkConfig
			result2 error
		})
	}
	fake.getNetworkConfigReturnsOnCall[i] = struct {
		result1 *network.NetworkConfig
		result2 error
	}{result1, result2}
}

func (fake *FakeNetworkStoreInterface) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeNetworkStoreInterface) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ network.NetworkStoreInterface = new(FakeNetworkStoreInterface)
