// Code generated by counterfeiter. DO NOT EDIT.
package networkfakes

import (
	"joblet/internal/joblet/network"
	"net"
	"sync"
)

type FakeDNS struct {
	CleanupDNSStub        func(string) error
	cleanupDNSMutex       sync.RWMutex
	cleanupDNSArgsForCall []struct {
		arg1 string
	}
	cleanupDNSReturns struct {
		result1 error
	}
	cleanupDNSReturnsOnCall map[int]struct {
		result1 error
	}
	GetHostnameStub        func(net.IP) (string, error)
	getHostnameMutex       sync.RWMutex
	getHostnameArgsForCall []struct {
		arg1 net.IP
	}
	getHostnameReturns struct {
		result1 string
		result2 error
	}
	getHostnameReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	ResolveNameStub        func(string) (net.IP, error)
	resolveNameMutex       sync.RWMutex
	resolveNameArgsForCall []struct {
		arg1 string
	}
	resolveNameReturns struct {
		result1 net.IP
		result2 error
	}
	resolveNameReturnsOnCall map[int]struct {
		result1 net.IP
		result2 error
	}
	SetupDNSStub        func(string, string, net.IP) error
	setupDNSMutex       sync.RWMutex
	setupDNSArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 net.IP
	}
	setupDNSReturns struct {
		result1 error
	}
	setupDNSReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDNS) CleanupDNS(arg1 string) error {
	fake.cleanupDNSMutex.Lock()
	ret, specificReturn := fake.cleanupDNSReturnsOnCall[len(fake.cleanupDNSArgsForCall)]
	fake.cleanupDNSArgsForCall = append(fake.cleanupDNSArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.CleanupDNSStub
	fakeReturns := fake.cleanupDNSReturns
	fake.recordInvocation("CleanupDNS", []interface{}{arg1})
	fake.cleanupDNSMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDNS) CleanupDNSCallCount() int {
	fake.cleanupDNSMutex.RLock()
	defer fake.cleanupDNSMutex.RUnlock()
	return len(fake.cleanupDNSArgsForCall)
}

func (fake *FakeDNS) CleanupDNSCalls(stub func(string) error) {
	fake.cleanupDNSMutex.Lock()
	defer fake.cleanupDNSMutex.Unlock()
	fake.CleanupDNSStub = stub
}

func (fake *FakeDNS) CleanupDNSArgsForCall(i int) string {
	fake.cleanupDNSMutex.RLock()
	defer fake.cleanupDNSMutex.RUnlock()
	argsForCall := fake.cleanupDNSArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDNS) CleanupDNSReturns(result1 error) {
	fake.cleanupDNSMutex.Lock()
	defer fake.cleanupDNSMutex.Unlock()
	fake.CleanupDNSStub = nil
	fake.cleanupDNSReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDNS) CleanupDNSReturnsOnCall(i int, result1 error) {
	fake.cleanupDNSMutex.Lock()
	defer fake.cleanupDNSMutex.Unlock()
	fake.CleanupDNSStub = nil
	if fake.cleanupDNSReturnsOnCall == nil {
		fake.cleanupDNSReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.cleanupDNSReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeDNS) GetHostname(arg1 net.IP) (string, error) {
	fake.getHostnameMutex.Lock()
	ret, specificReturn := fake.getHostnameReturnsOnCall[len(fake.getHostnameArgsForCall)]
	fake.getHostnameArgsForCall = append(fake.getHostnameArgsForCall, struct {
		arg1 net.IP
	}{arg1})
	stub := fake.GetHostnameStub
	fakeReturns := fake.getHostnameReturns
	fake.recordInvocation("GetHostname", []interface{}{arg1})
	fake.getHostnameMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDNS) GetHostnameCallCount() int {
	fake.getHostnameMutex.RLock()
	defer fake.getHostnameMutex.RUnlock()
	return len(fake.getHostnameArgsForCall)
}

func (fake *FakeDNS) GetHostnameCalls(stub func(net.IP) (string, error)) {
	fake.getHostnameMutex.Lock()
	defer fake.getHostnameMutex.Unlock()
	fake.GetHostnameStub = stub
}

func (fake *FakeDNS) GetHostnameArgsForCall(i int) net.IP {
	fake.getHostnameMutex.RLock()
	defer fake.getHostnameMutex.RUnlock()
	argsForCall := fake.getHostnameArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDNS) GetHostnameReturns(result1 string, result2 error) {
	fake.getHostnameMutex.Lock()
	defer fake.getHostnameMutex.Unlock()
	fake.GetHostnameStub = nil
	fake.getHostnameReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeDNS) GetHostnameReturnsOnCall(i int, result1 string, result2 error) {
	fake.getHostnameMutex.Lock()
	defer fake.getHostnameMutex.Unlock()
	fake.GetHostnameStub = nil
	if fake.getHostnameReturnsOnCall == nil {
		fake.getHostnameReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getHostnameReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeDNS) ResolveName(arg1 string) (net.IP, error) {
	fake.resolveNameMutex.Lock()
	ret, specificReturn := fake.resolveNameReturnsOnCall[len(fake.resolveNameArgsForCall)]
	fake.resolveNameArgsForCall = append(fake.resolveNameArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ResolveNameStub
	fakeReturns := fake.resolveNameReturns
	fake.recordInvocation("ResolveName", []interface{}{arg1})
	fake.resolveNameMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDNS) ResolveNameCallCount() int {
	fake.resolveNameMutex.RLock()
	defer fake.resolveNameMutex.RUnlock()
	return len(fake.resolveNameArgsForCall)
}

func (fake *FakeDNS) ResolveNameCalls(stub func(string) (net.IP, error)) {
	fake.resolveNameMutex.Lock()
	defer fake.resolveNameMutex.Unlock()
	fake.ResolveNameStub = stub
}

func (fake *FakeDNS) ResolveNameArgsForCall(i int) string {
	fake.resolveNameMutex.RLock()
	defer fake.resolveNameMutex.RUnlock()
	argsForCall := fake.resolveNameArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDNS) ResolveNameReturns(result1 net.IP, result2 error) {
	fake.resolveNameMutex.Lock()
	defer fake.resolveNameMutex.Unlock()
	fake.ResolveNameStub = nil
	fake.resolveNameReturns = struct {
		result1 net.IP
		result2 error
	}{result1, result2}
}

func (fake *FakeDNS) ResolveNameReturnsOnCall(i int, result1 net.IP, result2 error) {
	fake.resolveNameMutex.Lock()
	defer fake.resolveNameMutex.Unlock()
	fake.ResolveNameStub = nil
	if fake.resolveNameReturnsOnCall == nil {
		fake.resolveNameReturnsOnCall = make(map[int]struct {
			result1 net.IP
			result2 error
		})
	}
	fake.resolveNameReturnsOnCall[i] = struct {
		result1 net.IP
		result2 error
	}{result1, result2}
}

func (fake *FakeDNS) SetupDNS(arg1 string, arg2 string, arg3 net.IP) error {
	fake.setupDNSMutex.Lock()
	ret, specificReturn := fake.setupDNSReturnsOnCall[len(fake.setupDNSArgsForCall)]
	fake.setupDNSArgsForCall = append(fake.setupDNSArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 net.IP
	}{arg1, arg2, arg3})
	stub := fake.SetupDNSStub
	fakeReturns := fake.setupDNSReturns
	fake.recordInvocation("SetupDNS", []interface{}{arg1, arg2, arg3})
	fake.setupDNSMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDNS) SetupDNSCallCount() int {
	fake.setupDNSMutex.RLock()
	defer fake.setupDNSMutex.RUnlock()
	return len(fake.setupDNSArgsForCall)
}

func (fake *FakeDNS) SetupDNSCalls(stub func(string, string, net.IP) error) {
	fake.setupDNSMutex.Lock()
	defer fake.setupDNSMutex.Unlock()
	fake.SetupDNSStub = stub
}

func (fake *FakeDNS) SetupDNSArgsForCall(i int) (string, string, net.IP) {
	fake.setupDNSMutex.RLock()
	defer fake.setupDNSMutex.RUnlock()
	argsForCall := fake.setupDNSArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeDNS) SetupDNSReturns(result1 error) {
	fake.setupDNSMutex.Lock()
	defer fake.setupDNSMutex.Unlock()
	fake.SetupDNSStub = nil
	fake.setupDNSReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDNS) SetupDNSReturnsOnCall(i int, result1 error) {
	fake.setupDNSMutex.Lock()
	defer fake.setupDNSMutex.Unlock()
	fake.SetupDNSStub = nil
	if fake.setupDNSReturnsOnCall == nil {
		fake.setupDNSReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setupDNSReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeDNS) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDNS) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ network.DNS = new(FakeDNS)
