// Code generated by counterfeiter. DO NOT EDIT.
package networkfakes

import (
	"sync"

	"github.com/ehsaniara/joblet/internal/joblet/network"
)

type FakeValidator struct {
	ValidateCIDRStub        func(string) error
	validateCIDRMutex       sync.RWMutex
	validateCIDRArgsForCall []struct {
		arg1 string
	}
	validateCIDRReturns struct {
		result1 error
	}
	validateCIDRReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateJobNetworkingStub        func(string, string) error
	validateJobNetworkingMutex       sync.RWMutex
	validateJobNetworkingArgsForCall []struct {
		arg1 string
		arg2 string
	}
	validateJobNetworkingReturns struct {
		result1 error
	}
	validateJobNetworkingReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateNetworkConfigStub        func(*network.NetworkConfig) error
	validateNetworkConfigMutex       sync.RWMutex
	validateNetworkConfigArgsForCall []struct {
		arg1 *network.NetworkConfig
	}
	validateNetworkConfigReturns struct {
		result1 error
	}
	validateNetworkConfigReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateNetworkNameStub        func(string) error
	validateNetworkNameMutex       sync.RWMutex
	validateNetworkNameArgsForCall []struct {
		arg1 string
	}
	validateNetworkNameReturns struct {
		result1 error
	}
	validateNetworkNameReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeValidator) ValidateCIDR(arg1 string) error {
	fake.validateCIDRMutex.Lock()
	ret, specificReturn := fake.validateCIDRReturnsOnCall[len(fake.validateCIDRArgsForCall)]
	fake.validateCIDRArgsForCall = append(fake.validateCIDRArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ValidateCIDRStub
	fakeReturns := fake.validateCIDRReturns
	fake.recordInvocation("ValidateCIDR", []interface{}{arg1})
	fake.validateCIDRMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeValidator) ValidateCIDRCallCount() int {
	fake.validateCIDRMutex.RLock()
	defer fake.validateCIDRMutex.RUnlock()
	return len(fake.validateCIDRArgsForCall)
}

func (fake *FakeValidator) ValidateCIDRCalls(stub func(string) error) {
	fake.validateCIDRMutex.Lock()
	defer fake.validateCIDRMutex.Unlock()
	fake.ValidateCIDRStub = stub
}

func (fake *FakeValidator) ValidateCIDRArgsForCall(i int) string {
	fake.validateCIDRMutex.RLock()
	defer fake.validateCIDRMutex.RUnlock()
	argsForCall := fake.validateCIDRArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeValidator) ValidateCIDRReturns(result1 error) {
	fake.validateCIDRMutex.Lock()
	defer fake.validateCIDRMutex.Unlock()
	fake.ValidateCIDRStub = nil
	fake.validateCIDRReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeValidator) ValidateCIDRReturnsOnCall(i int, result1 error) {
	fake.validateCIDRMutex.Lock()
	defer fake.validateCIDRMutex.Unlock()
	fake.ValidateCIDRStub = nil
	if fake.validateCIDRReturnsOnCall == nil {
		fake.validateCIDRReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateCIDRReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeValidator) ValidateJobNetworking(arg1 string, arg2 string) error {
	fake.validateJobNetworkingMutex.Lock()
	ret, specificReturn := fake.validateJobNetworkingReturnsOnCall[len(fake.validateJobNetworkingArgsForCall)]
	fake.validateJobNetworkingArgsForCall = append(fake.validateJobNetworkingArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.ValidateJobNetworkingStub
	fakeReturns := fake.validateJobNetworkingReturns
	fake.recordInvocation("ValidateJobNetworking", []interface{}{arg1, arg2})
	fake.validateJobNetworkingMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeValidator) ValidateJobNetworkingCallCount() int {
	fake.validateJobNetworkingMutex.RLock()
	defer fake.validateJobNetworkingMutex.RUnlock()
	return len(fake.validateJobNetworkingArgsForCall)
}

func (fake *FakeValidator) ValidateJobNetworkingCalls(stub func(string, string) error) {
	fake.validateJobNetworkingMutex.Lock()
	defer fake.validateJobNetworkingMutex.Unlock()
	fake.ValidateJobNetworkingStub = stub
}

func (fake *FakeValidator) ValidateJobNetworkingArgsForCall(i int) (string, string) {
	fake.validateJobNetworkingMutex.RLock()
	defer fake.validateJobNetworkingMutex.RUnlock()
	argsForCall := fake.validateJobNetworkingArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeValidator) ValidateJobNetworkingReturns(result1 error) {
	fake.validateJobNetworkingMutex.Lock()
	defer fake.validateJobNetworkingMutex.Unlock()
	fake.ValidateJobNetworkingStub = nil
	fake.validateJobNetworkingReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeValidator) ValidateJobNetworkingReturnsOnCall(i int, result1 error) {
	fake.validateJobNetworkingMutex.Lock()
	defer fake.validateJobNetworkingMutex.Unlock()
	fake.ValidateJobNetworkingStub = nil
	if fake.validateJobNetworkingReturnsOnCall == nil {
		fake.validateJobNetworkingReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateJobNetworkingReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeValidator) ValidateNetworkConfig(arg1 *network.NetworkConfig) error {
	fake.validateNetworkConfigMutex.Lock()
	ret, specificReturn := fake.validateNetworkConfigReturnsOnCall[len(fake.validateNetworkConfigArgsForCall)]
	fake.validateNetworkConfigArgsForCall = append(fake.validateNetworkConfigArgsForCall, struct {
		arg1 *network.NetworkConfig
	}{arg1})
	stub := fake.ValidateNetworkConfigStub
	fakeReturns := fake.validateNetworkConfigReturns
	fake.recordInvocation("ValidateNetworkConfig", []interface{}{arg1})
	fake.validateNetworkConfigMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeValidator) ValidateNetworkConfigCallCount() int {
	fake.validateNetworkConfigMutex.RLock()
	defer fake.validateNetworkConfigMutex.RUnlock()
	return len(fake.validateNetworkConfigArgsForCall)
}

func (fake *FakeValidator) ValidateNetworkConfigCalls(stub func(*network.NetworkConfig) error) {
	fake.validateNetworkConfigMutex.Lock()
	defer fake.validateNetworkConfigMutex.Unlock()
	fake.ValidateNetworkConfigStub = stub
}

func (fake *FakeValidator) ValidateNetworkConfigArgsForCall(i int) *network.NetworkConfig {
	fake.validateNetworkConfigMutex.RLock()
	defer fake.validateNetworkConfigMutex.RUnlock()
	argsForCall := fake.validateNetworkConfigArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeValidator) ValidateNetworkConfigReturns(result1 error) {
	fake.validateNetworkConfigMutex.Lock()
	defer fake.validateNetworkConfigMutex.Unlock()
	fake.ValidateNetworkConfigStub = nil
	fake.validateNetworkConfigReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeValidator) ValidateNetworkConfigReturnsOnCall(i int, result1 error) {
	fake.validateNetworkConfigMutex.Lock()
	defer fake.validateNetworkConfigMutex.Unlock()
	fake.ValidateNetworkConfigStub = nil
	if fake.validateNetworkConfigReturnsOnCall == nil {
		fake.validateNetworkConfigReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateNetworkConfigReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeValidator) ValidateNetworkName(arg1 string) error {
	fake.validateNetworkNameMutex.Lock()
	ret, specificReturn := fake.validateNetworkNameReturnsOnCall[len(fake.validateNetworkNameArgsForCall)]
	fake.validateNetworkNameArgsForCall = append(fake.validateNetworkNameArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ValidateNetworkNameStub
	fakeReturns := fake.validateNetworkNameReturns
	fake.recordInvocation("ValidateNetworkName", []interface{}{arg1})
	fake.validateNetworkNameMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeValidator) ValidateNetworkNameCallCount() int {
	fake.validateNetworkNameMutex.RLock()
	defer fake.validateNetworkNameMutex.RUnlock()
	return len(fake.validateNetworkNameArgsForCall)
}

func (fake *FakeValidator) ValidateNetworkNameCalls(stub func(string) error) {
	fake.validateNetworkNameMutex.Lock()
	defer fake.validateNetworkNameMutex.Unlock()
	fake.ValidateNetworkNameStub = stub
}

func (fake *FakeValidator) ValidateNetworkNameArgsForCall(i int) string {
	fake.validateNetworkNameMutex.RLock()
	defer fake.validateNetworkNameMutex.RUnlock()
	argsForCall := fake.validateNetworkNameArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeValidator) ValidateNetworkNameReturns(result1 error) {
	fake.validateNetworkNameMutex.Lock()
	defer fake.validateNetworkNameMutex.Unlock()
	fake.ValidateNetworkNameStub = nil
	fake.validateNetworkNameReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeValidator) ValidateNetworkNameReturnsOnCall(i int, result1 error) {
	fake.validateNetworkNameMutex.Lock()
	defer fake.validateNetworkNameMutex.Unlock()
	fake.ValidateNetworkNameStub = nil
	if fake.validateNetworkNameReturnsOnCall == nil {
		fake.validateNetworkNameReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateNetworkNameReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeValidator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeValidator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ network.Validator = new(FakeValidator)
